/**
 * Curated default search destinations + sensible default search phrases.
 *
 * Derived from the frontend module menu registrations (each module's
 * `initialize*()` `addItems(...)` menu tree). This seed is used ONCE on an
 * empty collection; thereafter the live `POST /api/search-destinations/sync`
 * endpoint keeps the collection reconciled with the running app's menus, and
 * users may add/edit keywords without seeding ever clobbering them.
 *
 * `resource` mirrors the menu item `resource` so the frontend can hide
 * destinations the current user cannot access.
 */
export interface DefaultDestination {
  key: string;
  label: string;
  route: string;
  icon?: string;
  group?: string;
  keywords?: string[];
  description?: string;
  resource?: string;
  scope?: string;
}

export const DEFAULT_SEARCH_DESTINATIONS: DefaultDestination[] = [
  // ----- Core -----
  {
    key: "home",
    label: "Home",
    route: "/home",
    icon: "pi pi-home",
    group: "General",
    keywords: ["home", "start", "dashboard", "main"],
    description: "Application home page",
    scope: "base-app/routing",
  },
  {
    key: "contacts",
    label: "Contacts",
    route: "/contacts",
    icon: "pi pi-address-book",
    group: "General",
    keywords: ["contacts", "people", "customers", "clients", "address book"],
    resource: "contacts/menu",
    scope: "base-app/routing",
  },

  // ----- Sales -----
  {
    key: "sales.dashboard",
    label: "Sales Dashboard",
    route: "/sales/dashboard",
    icon: "pi pi-th-large",
    group: "Sales",
    keywords: ["sales", "dashboard", "kpi", "revenue", "overview"],
    resource: "sales/dashboard/menu",
    scope: "sales",
  },
  {
    key: "sales.opportunities",
    label: "Opportunities",
    route: "/sales/opportunities",
    icon: "pi pi-list",
    group: "Sales",
    keywords: ["crm", "deals", "opportunities", "pipeline", "leads", "sales"],
    resource: "sales/opportunities/menu",
    scope: "sales",
  },
  {
    key: "sales.orders",
    label: "Sales Orders",
    route: "/sales/orders",
    icon: "pi pi-shopping-cart",
    group: "Sales",
    keywords: ["orders", "sales orders", "so", "closed orders", "sales"],
    resource: "sales/orders/menu",
    scope: "sales",
  },
  {
    key: "sales.targets",
    label: "Sales Targets",
    route: "/sales/targets/list",
    icon: "pi pi-flag",
    group: "Sales",
    keywords: ["targets", "goals", "quota", "sales targets"],
    resource: "sales/targets/menu",
    scope: "sales",
  },
  {
    key: "pricing.estimates.new",
    label: "Estimated Pricing",
    route: "/pricing/estimates/new",
    icon: "pi pi-calculator",
    group: "Sales",
    keywords: ["pricing", "estimate", "quote", "estimated pricing", "ai"],
    resource: "pricing-estimates/menu",
    scope: "pricing-estimates",
  },
  {
    key: "pricing.estimates.history",
    label: "Pricing History",
    route: "/pricing/estimates/history",
    icon: "pi pi-history",
    group: "Sales",
    keywords: ["pricing history", "estimates", "quotes", "past estimates"],
    resource: "pricing-estimates/menu",
    scope: "pricing-estimates",
  },

  // ----- Purchases -----
  {
    key: "purchases.suppliers",
    label: "Suppliers",
    route: "/purchases/suppliers",
    icon: "pi pi-truck",
    group: "Purchases",
    keywords: ["suppliers", "vendors", "purchases", "procurement"],
    resource: "purchases/menu",
    scope: "purchases",
  },
  {
    key: "purchases.orders",
    label: "Purchase Orders",
    route: "/purchases/orders",
    icon: "pi pi-shopping-bag",
    group: "Purchases",
    keywords: ["purchase orders", "po", "orders", "purchases", "procurement"],
    resource: "purchases/menu",
    scope: "purchases",
  },
  {
    key: "purchases.pipeline",
    label: "Purchase Pipeline",
    route: "/purchases/pipeline",
    icon: "pi pi-sitemap",
    group: "Purchases",
    keywords: ["pipeline", "kanban", "purchases", "stages"],
    resource: "purchases/menu",
    scope: "purchases",
  },

  // ----- Inventory -----
  {
    key: "inventory.warehouses",
    label: "Warehouses",
    route: "/inventory/warehouses",
    icon: "pi pi-building",
    group: "Inventory",
    keywords: ["warehouses", "inventory", "stock", "locations"],
    resource: "inventory/menu",
    scope: "inventory",
  },
  {
    key: "inventory.products",
    label: "Products",
    route: "/inventory/products",
    icon: "pi pi-box",
    group: "Inventory",
    keywords: ["products", "items", "sku", "inventory", "catalog"],
    resource: "inventory/menu",
    scope: "inventory",
  },
  {
    key: "inventory.movements",
    label: "Stock Movements",
    route: "/inventory/movements",
    icon: "pi pi-arrows-h",
    group: "Inventory",
    keywords: ["movements", "stock movements", "in", "out", "adjustment"],
    resource: "inventory/menu",
    scope: "inventory",
  },
  {
    key: "inventory.transfer",
    label: "Stock Transfer",
    route: "/inventory/transfer",
    icon: "pi pi-arrow-right-arrow-left",
    group: "Inventory",
    keywords: ["transfer", "stock transfer", "move stock", "inventory"],
    resource: "inventory/menu",
    scope: "inventory",
  },
  {
    key: "inventory.uom-categories",
    label: "UoM Categories",
    route: "/inventory/uom-categories",
    icon: "pi pi-tags",
    group: "Inventory",
    keywords: ["uom", "unit of measure", "categories", "inventory"],
    resource: "inventory/menu",
    scope: "inventory",
  },
  {
    key: "inventory.uoms",
    label: "Units of Measure",
    route: "/inventory/uoms",
    icon: "pi pi-tag",
    group: "Inventory",
    keywords: ["uom", "units of measure", "unit", "inventory"],
    resource: "inventory/menu",
    scope: "inventory",
  },

  // ----- Accounting -----
  {
    key: "accounting.invoices",
    label: "Invoices",
    route: "/accounting/invoices",
    icon: "pi pi-file",
    group: "Accounting",
    keywords: ["invoices", "billing", "accounting", "ar"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.accounts",
    label: "Accounts",
    route: "/accounting/accounts",
    icon: "pi pi-wallet",
    group: "Accounting",
    keywords: ["accounts", "chart of accounts", "coa", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.journals",
    label: "Journals",
    route: "/accounting/journals",
    icon: "pi pi-book",
    group: "Accounting",
    keywords: ["journals", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.journal-entries",
    label: "Journal Entries",
    route: "/accounting/journal-entries",
    icon: "pi pi-list",
    group: "Accounting",
    keywords: ["journal entries", "entries", "ledger", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.payments",
    label: "Payments",
    route: "/accounting/payments",
    icon: "pi pi-credit-card",
    group: "Accounting",
    keywords: ["payments", "accounting", "receipts"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.taxes",
    label: "Taxes",
    route: "/accounting/taxes",
    icon: "pi pi-percentage",
    group: "Accounting",
    keywords: ["taxes", "tax", "vat", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.discounts",
    label: "Discounts",
    route: "/accounting/discounts",
    icon: "pi pi-tag",
    group: "Accounting",
    keywords: ["discounts", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.fiscal-positions",
    label: "Fiscal Positions",
    route: "/accounting/fiscal-positions",
    icon: "pi pi-map",
    group: "Accounting",
    keywords: ["fiscal positions", "tax mapping", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },
  {
    key: "accounting.payment-terms",
    label: "Payment Terms",
    route: "/accounting/payment-terms",
    icon: "pi pi-calendar",
    group: "Accounting",
    keywords: ["payment terms", "terms", "due dates", "accounting"],
    resource: "accounting/menu",
    scope: "accounting",
  },

  // ----- Tasks & Projects -----
  {
    key: "tasks",
    label: "Tasks",
    route: "/tasks",
    icon: "pi pi-check-square",
    group: "Tasks",
    keywords: ["tasks", "todo", "to do", "work items"],
    resource: "tasks/menu",
    scope: "tasks",
  },
  {
    key: "projects",
    label: "Projects",
    route: "/projects",
    icon: "pi pi-folder",
    group: "Projects",
    keywords: ["projects", "project management"],
    resource: "projects/menu",
    scope: "projects",
  },

  // ----- Asset Roster -----
  {
    key: "asset-roster",
    label: "Asset Roster",
    route: "/asset-roster",
    icon: "pi pi-server",
    group: "Assets",
    keywords: ["assets", "asset roster", "equipment", "inventory of assets"],
    resource: "asset-roster/menu",
    scope: "asset-roster",
  },

  // ----- Helpdesk -----
  {
    key: "helpdesk",
    label: "Helpdesk",
    route: "/helpdesk",
    icon: "pi pi-ticket",
    group: "Helpdesk",
    keywords: ["helpdesk", "tickets", "support", "service desk"],
    resource: "helpdesk/menu",
    scope: "helpdesk",
  },

  // ----- Email Marketing -----
  {
    key: "email-marketing.dashboard",
    label: "Email Marketing Dashboard",
    route: "/email-marketing/dashboard",
    icon: "pi pi-th-large",
    group: "Email Marketing",
    keywords: ["email marketing", "dashboard", "campaigns overview"],
    resource: "email-marketing/menu",
    scope: "email-marketing",
  },
  {
    key: "email-marketing.campaigns",
    label: "Campaigns",
    route: "/email-marketing/campaigns",
    icon: "pi pi-send",
    group: "Email Marketing",
    keywords: ["campaigns", "email campaigns", "email marketing", "newsletter"],
    resource: "email-marketing/menu",
    scope: "email-marketing",
  },
  {
    key: "email-marketing.templates",
    label: "Email Templates",
    route: "/email-marketing/templates",
    icon: "pi pi-file-edit",
    group: "Email Marketing",
    keywords: ["templates", "email templates", "email marketing", "designs"],
    resource: "email-marketing/menu",
    scope: "email-marketing",
  },
  {
    key: "email-marketing.lists",
    label: "Mailing Lists",
    route: "/email-marketing/lists",
    icon: "pi pi-list",
    group: "Email Marketing",
    keywords: ["mailing lists", "lists", "audience", "email marketing"],
    resource: "email-marketing/menu",
    scope: "email-marketing",
  },
  {
    key: "email-marketing.subscribers",
    label: "Subscribers",
    route: "/email-marketing/subscribers",
    icon: "pi pi-users",
    group: "Email Marketing",
    keywords: ["subscribers", "contacts", "audience", "email marketing"],
    resource: "email-marketing/menu",
    scope: "email-marketing",
  },

  // ----- Settings -----
  {
    key: "settings.companies",
    label: "Companies",
    route: "/settings/companies",
    icon: "pi pi-building",
    group: "Settings",
    keywords: ["companies", "company", "settings", "organizations"],
    resource: "companies/menu",
    scope: "base-app/companies",
  },
  {
    key: "settings.users",
    label: "Users",
    route: "/settings/users",
    icon: "pi pi-user",
    group: "Settings",
    keywords: ["users", "accounts", "settings", "people"],
    resource: "users/menu",
    scope: "base-app/users",
  },
  {
    key: "settings.roles",
    label: "Roles",
    route: "/settings/roles",
    icon: "pi pi-users",
    group: "Settings",
    keywords: ["roles", "permissions", "settings", "rbac"],
    resource: "roles/menu",
    scope: "base-app/roles",
  },
  {
    key: "settings.policies",
    label: "Policies",
    route: "/settings/policies",
    icon: "pi pi-check",
    group: "Settings",
    keywords: ["policies", "permissions", "settings", "rbac"],
    resource: "policies/menu",
    scope: "base-app/policies",
  },
  {
    key: "settings.countries",
    label: "Countries",
    route: "/settings/countries",
    icon: "pi pi-globe",
    group: "Settings",
    keywords: ["countries", "settings", "geography"],
    resource: "countries/menu",
    scope: "base-app/countries",
  },
  {
    key: "settings.currencies",
    label: "Currencies",
    route: "/settings/currencies",
    icon: "pi pi-dollar",
    group: "Settings",
    keywords: ["currencies", "currency", "settings", "exchange"],
    resource: "currencies/menu",
    scope: "base-app/currency",
  },
  {
    key: "settings.reporting",
    label: "Reporting",
    route: "/settings/reporting",
    icon: "pi pi-file-pdf",
    group: "Settings",
    keywords: ["reporting", "reports", "settings"],
    resource: "reporting/menu",
    scope: "base-app/reporting",
  },
  {
    key: "settings.templates",
    label: "Templates",
    route: "/settings/templates",
    icon: "pi pi-file-pdf",
    group: "Settings",
    keywords: ["templates", "settings", "documents"],
    resource: "templates/menu",
    scope: "base-app/templates",
  },
  {
    key: "settings.sequences",
    label: "Sequences",
    route: "/settings/sequences",
    icon: "pi pi-sort-numeric-up",
    group: "Settings",
    keywords: ["sequences", "numbering", "document numbers", "settings"],
    resource: "sequences/menu",
    scope: "base-app/sequences",
  },
  {
    key: "settings.ai-settings",
    label: "AI Configuration",
    route: "/settings/ai-settings",
    icon: "pi pi-microchip",
    group: "Settings",
    keywords: ["ai", "ai configuration", "gemini", "settings"],
    resource: "ai-settings/menu",
    scope: "base-app/ai-settings",
  },
  {
    key: "settings.drive-settings",
    label: "Google Drive Configuration",
    route: "/settings/drive-settings",
    icon: "pi pi-cloud",
    group: "Settings",
    keywords: ["google drive", "drive", "configuration", "settings"],
    resource: "drive-settings/menu",
    scope: "base-app/drive-settings",
  },
  {
    key: "settings.sales.crm-stages",
    label: "CRM Stages",
    route: "/settings/sales/crm-stages",
    icon: "pi pi-list",
    group: "Settings",
    keywords: ["crm stages", "deal stages", "pipeline stages", "settings"],
    resource: "crm-stages/menu",
    scope: "sales",
  },
  {
    key: "settings.sales.order-stages",
    label: "Order Stages",
    route: "/settings/sales/order-stages",
    icon: "pi pi-tag",
    group: "Settings",
    keywords: ["order stages", "sales order stages", "settings"],
    resource: "sales-order-stages/menu",
    scope: "sales",
  },
  {
    key: "settings.sales.configuration",
    label: "Sales Configuration",
    route: "/settings/sales/configuration",
    icon: "pi pi-cog",
    group: "Settings",
    keywords: ["sales configuration", "sales settings", "settings"],
    resource: "sales/configuration/menu",
    scope: "sales",
  },
  {
    key: "settings.pricing.configuration",
    label: "Pricing Configuration",
    route: "/settings/pricing/configuration",
    icon: "pi pi-calculator",
    group: "Settings",
    keywords: ["pricing configuration", "pricing settings", "settings"],
    resource: "pricing-settings/menu",
    scope: "base-app/pricing-estimates",
  },
  {
    key: "settings.purchases.purchase-stages",
    label: "Purchase Stages",
    route: "/settings/purchases/purchase-stages",
    icon: "pi pi-list",
    group: "Settings",
    keywords: ["purchase stages", "pipeline stages", "settings"],
    resource: "purchase-stages/menu",
    scope: "purchases",
  },
  {
    key: "settings.purchases.configuration",
    label: "Purchases Configuration",
    route: "/settings/purchases/configuration",
    icon: "pi pi-cog",
    group: "Settings",
    keywords: ["purchases configuration", "purchase settings", "settings"],
    resource: "purchases/settings/menu",
    scope: "purchases",
  },
  {
    key: "settings.inventory.product-types",
    label: "Product Types",
    route: "/settings/inventory/product-types",
    icon: "pi pi-tags",
    group: "Settings",
    keywords: ["product types", "inventory", "settings"],
    resource: "inventory/menu",
    scope: "inventory",
  },
  {
    key: "settings.accounting.configuration",
    label: "Accounting Configuration",
    route: "/settings/accounting/configuration",
    icon: "pi pi-cog",
    group: "Settings",
    keywords: ["accounting configuration", "accounting settings", "settings"],
    resource: "accounting/menu",
    scope: "base-app/accounting",
  },
  {
    key: "settings.tasks.task-stages",
    label: "Task Stages",
    route: "/settings/tasks/task-stages",
    icon: "pi pi-list",
    group: "Settings",
    keywords: ["task stages", "tasks", "settings"],
    resource: "task-stages/menu",
    scope: "tasks",
  },
  {
    key: "settings.tasks.task-types",
    label: "Task Types",
    route: "/settings/tasks/task-types",
    icon: "pi pi-tags",
    group: "Settings",
    keywords: ["task types", "tasks", "settings"],
    resource: "task-types/menu",
    scope: "tasks",
  },
  {
    key: "settings.projects.project-stages",
    label: "Project Stages",
    route: "/settings/projects/project-stages",
    icon: "pi pi-list",
    group: "Settings",
    keywords: ["project stages", "projects", "settings"],
    resource: "project-stages/menu",
    scope: "projects",
  },
  {
    key: "settings.helpdesk.helpdesk-stages",
    label: "Ticket Stages",
    route: "/settings/helpdesk/helpdesk-stages",
    icon: "pi pi-list",
    group: "Settings",
    keywords: ["ticket stages", "helpdesk stages", "settings"],
    resource: "helpdesk-stages/menu",
    scope: "helpdesk",
  },
  {
    key: "settings.asset-roster.maintenance-windows",
    label: "Maintenance Windows",
    route: "/settings/asset-roster/maintenance-windows",
    icon: "pi pi-calendar",
    group: "Settings",
    keywords: ["maintenance windows", "assets", "settings"],
    resource: "maintenance-windows/menu",
    scope: "asset-roster",
  },
  {
    key: "settings.asset-roster.rooms",
    label: "Rooms",
    route: "/settings/asset-roster/rooms",
    icon: "pi pi-home",
    group: "Settings",
    keywords: ["rooms", "assets", "facilities", "settings"],
    resource: "rooms/menu",
    scope: "asset-roster",
  },
  {
    key: "settings.asset-roster.facilities",
    label: "Facilities",
    route: "/settings/asset-roster/facilities",
    icon: "pi pi-building",
    group: "Settings",
    keywords: ["facilities", "assets", "settings"],
    resource: "facilities/menu",
    scope: "asset-roster",
  },
  {
    key: "settings.asset-roster.asset-types",
    label: "Asset Types",
    route: "/settings/asset-roster/asset-types",
    icon: "pi pi-tags",
    group: "Settings",
    keywords: ["asset types", "assets", "settings"],
    resource: "asset-types/menu",
    scope: "asset-roster",
  },
  {
    key: "settings.email-marketing.config",
    label: "Email Marketing Configuration",
    route: "/settings/email-marketing/config",
    icon: "pi pi-cog",
    group: "Settings",
    keywords: [
      "email marketing configuration",
      "esp",
      "email settings",
      "settings",
    ],
    resource: "email-marketing/menu",
    scope: "email-marketing",
  },
];
