export { countryRouter } from "./countries/routes/country-routes";
export { companyRouter } from "./companies/routes/company-routes";
export { contactRouter } from "./contacts/routes/contact-routes";
export { productTypeRouter } from "./product-types/routes/product-type-routes";
export { maintenanceWindowRouter } from "./maintenance-windows/routes/maintenance-window-routes";
export { facilityRouter } from "./facilities/routes/facility-routes";
export { roomRouter } from "./facilities/routes/room-routes";
export { productRouter } from "./products/routes/product-routes";
export { productComissioningRouter } from "./product-comissioning/routes/product-comissioning-routes";
