/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from "mongoose";

/**
 * Lean version of ActivityHistoryDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ActivityHistoryDocument.toObject()`. To avoid conflicts with model names, use the type alias `ActivityHistoryObject`.
 * ```
 * const activityhistoryObject = activityhistory.toObject();
 * ```
 */
export type ActivityHistory = {
  title: string;
  details?: string;
  performDate: Date;
  model: string;
  modelId: mongoose.Types.ObjectId;
  metadata?: any | null;
  userId?: User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ActivityHistoryDocument (type alias of `ActivityHistory`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { ActivityHistory } from "../models"
 * import { ActivityHistoryObject } from "../interfaces/mongoose.gen.ts"
 *
 * const activityhistoryObject: ActivityHistoryObject = activityhistory.toObject();
 * ```
 */
export type ActivityHistoryObject = ActivityHistory;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ActivityHistoryQuery = mongoose.Query<
  any,
  ActivityHistoryDocument,
  ActivityHistoryQueries
> &
  ActivityHistoryQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ActivityHistorySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ActivityHistoryQueries = {
  paginate: (
    this: ActivityHistoryQuery,
    ...args: any[]
  ) => ActivityHistoryQuery;
};

export type ActivityHistoryMethods = {};

export type ActivityHistoryStatics = {
  paginate: (this: ActivityHistoryModel, ...args: any[]) => any;
  paginateSubDocs: (this: ActivityHistoryModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ActivityHistory = mongoose.model<ActivityHistoryDocument, ActivityHistoryModel>("ActivityHistory", ActivityHistorySchema);
 * ```
 */
export type ActivityHistoryModel = mongoose.Model<
  ActivityHistoryDocument,
  ActivityHistoryQueries
> &
  ActivityHistoryStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new ActivityHistory schema instances:
 * ```
 * const ActivityHistorySchema: ActivityHistorySchema = new mongoose.Schema({ ... })
 * ```
 */
export type ActivityHistorySchema = mongoose.Schema<
  ActivityHistoryDocument,
  ActivityHistoryModel,
  ActivityHistoryMethods,
  ActivityHistoryQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ActivityHistory = mongoose.model<ActivityHistoryDocument, ActivityHistoryModel>("ActivityHistory", ActivityHistorySchema);
 * ```
 */
export type ActivityHistoryDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ActivityHistoryQueries
> &
  ActivityHistoryMethods & {
    title: string;
    details?: string;
    performDate: Date;
    model: string;
    modelId: mongoose.Types.ObjectId;
    metadata?: any | null;
    userId?: UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of AssetCommissioningAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetCommissioningDocument.toObject()`.
 * ```
 * const assetcommissioningObject = assetcommissioning.toObject();
 * ```
 */
export type AssetCommissioningAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of AssetCommissioningDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetCommissioningDocument.toObject()`. To avoid conflicts with model names, use the type alias `AssetCommissioningObject`.
 * ```
 * const assetcommissioningObject = assetcommissioning.toObject();
 * ```
 */
export type AssetCommissioning = {
  outcome: "fail" | "pass";
  details?: string;
  attachments: AssetCommissioningAttachment[];
  assetRosterId: AssetRoster;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of AssetCommissioningDocument (type alias of `AssetCommissioning`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { AssetCommissioning } from "../models"
 * import { AssetCommissioningObject } from "../interfaces/mongoose.gen.ts"
 *
 * const assetcommissioningObject: AssetCommissioningObject = assetcommissioning.toObject();
 * ```
 */
export type AssetCommissioningObject = AssetCommissioning;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type AssetCommissioningQuery = mongoose.Query<
  any,
  AssetCommissioningDocument,
  AssetCommissioningQueries
> &
  AssetCommissioningQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `AssetCommissioningSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type AssetCommissioningQueries = {
  paginate: (
    this: AssetCommissioningQuery,
    ...args: any[]
  ) => AssetCommissioningQuery;
};

export type AssetCommissioningMethods = {};

export type AssetCommissioningStatics = {
  paginate: (this: AssetCommissioningModel, ...args: any[]) => any;
  paginateSubDocs: (this: AssetCommissioningModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetCommissioning = mongoose.model<AssetCommissioningDocument, AssetCommissioningModel>("AssetCommissioning", AssetCommissioningSchema);
 * ```
 */
export type AssetCommissioningModel = mongoose.Model<
  AssetCommissioningDocument,
  AssetCommissioningQueries
> &
  AssetCommissioningStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new AssetCommissioning schema instances:
 * ```
 * const AssetCommissioningSchema: AssetCommissioningSchema = new mongoose.Schema({ ... })
 * ```
 */
export type AssetCommissioningSchema = mongoose.Schema<
  AssetCommissioningDocument,
  AssetCommissioningModel,
  AssetCommissioningMethods,
  AssetCommissioningQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `AssetCommissioningDocument["attachments"]` element.
 */
export type AssetCommissioningAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetCommissioning = mongoose.model<AssetCommissioningDocument, AssetCommissioningModel>("AssetCommissioning", AssetCommissioningSchema);
 * ```
 */
export type AssetCommissioningDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  AssetCommissioningQueries
> &
  AssetCommissioningMethods & {
    outcome: "fail" | "pass";
    details?: string;
    attachments: mongoose.Types.DocumentArray<AssetCommissioningAttachmentDocument>;
    assetRosterId: AssetRosterDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of AssetMaintenanceAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetMaintenanceDocument.toObject()`.
 * ```
 * const assetmaintenanceObject = assetmaintenance.toObject();
 * ```
 */
export type AssetMaintenanceAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of AssetMaintenanceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetMaintenanceDocument.toObject()`. To avoid conflicts with model names, use the type alias `AssetMaintenanceObject`.
 * ```
 * const assetmaintenanceObject = assetmaintenance.toObject();
 * ```
 */
export type AssetMaintenance = {
  name: string;
  description?: string;
  notes?: string;
  attachments: AssetMaintenanceAttachment[];
  assetRosterId: AssetRoster;
  dateStart?: Date;
  dateEnd?: Date;
  type: "service" | "preventive-maintenance";
  manual?: boolean;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of AssetMaintenanceDocument (type alias of `AssetMaintenance`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { AssetMaintenance } from "../models"
 * import { AssetMaintenanceObject } from "../interfaces/mongoose.gen.ts"
 *
 * const assetmaintenanceObject: AssetMaintenanceObject = assetmaintenance.toObject();
 * ```
 */
export type AssetMaintenanceObject = AssetMaintenance;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type AssetMaintenanceQuery = mongoose.Query<
  any,
  AssetMaintenanceDocument,
  AssetMaintenanceQueries
> &
  AssetMaintenanceQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `AssetMaintenanceSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type AssetMaintenanceQueries = {
  paginate: (
    this: AssetMaintenanceQuery,
    ...args: any[]
  ) => AssetMaintenanceQuery;
};

export type AssetMaintenanceMethods = {};

export type AssetMaintenanceStatics = {
  paginate: (this: AssetMaintenanceModel, ...args: any[]) => any;
  paginateSubDocs: (this: AssetMaintenanceModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetMaintenance = mongoose.model<AssetMaintenanceDocument, AssetMaintenanceModel>("AssetMaintenance", AssetMaintenanceSchema);
 * ```
 */
export type AssetMaintenanceModel = mongoose.Model<
  AssetMaintenanceDocument,
  AssetMaintenanceQueries
> &
  AssetMaintenanceStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new AssetMaintenance schema instances:
 * ```
 * const AssetMaintenanceSchema: AssetMaintenanceSchema = new mongoose.Schema({ ... })
 * ```
 */
export type AssetMaintenanceSchema = mongoose.Schema<
  AssetMaintenanceDocument,
  AssetMaintenanceModel,
  AssetMaintenanceMethods,
  AssetMaintenanceQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `AssetMaintenanceDocument["attachments"]` element.
 */
export type AssetMaintenanceAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetMaintenance = mongoose.model<AssetMaintenanceDocument, AssetMaintenanceModel>("AssetMaintenance", AssetMaintenanceSchema);
 * ```
 */
export type AssetMaintenanceDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  AssetMaintenanceQueries
> &
  AssetMaintenanceMethods & {
    name: string;
    description?: string;
    notes?: string;
    attachments: mongoose.Types.DocumentArray<AssetMaintenanceAttachmentDocument>;
    assetRosterId: AssetRosterDocument;
    dateStart?: Date;
    dateEnd?: Date;
    type: "service" | "preventive-maintenance";
    manual?: boolean;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of AssetRosterAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetRosterDocument.toObject()`.
 * ```
 * const assetrosterObject = assetroster.toObject();
 * ```
 */
export type AssetRosterAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of AssetRosterDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetRosterDocument.toObject()`. To avoid conflicts with model names, use the type alias `AssetRosterObject`.
 * ```
 * const assetrosterObject = assetroster.toObject();
 * ```
 */
export type AssetRoster = {
  assetTypeIds: AssetType[];
  vendorIds?: Contact[];
  makeIds: Contact[];
  productModel: string;
  serialNumber: string;
  acquiredDate: Date;
  acquiredPrice?: number;
  currentPrice?: number;
  condition?: "excellent" | "good" | "fair" | "poor";
  maintenanceWindowIds: MaintenanceWindow[];
  photo?: mongoose.Types.ObjectId;
  locationId?: Room;
  warrantyDate?: Date;
  remarks?: string;
  status?:
    | "active"
    | "awaiting-commissioning"
    | "under-service"
    | "decommissioned"
    | "in-pm";
  minMaintenanceDate?: Date;
  maintenanceDate?: Date;
  maxMaintenanceDate?: Date;
  attachments: AssetRosterAttachment[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  assetCommission: any;
  assetMaintenances: any;
};

/**
 * Lean version of AssetRosterDocument (type alias of `AssetRoster`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { AssetRoster } from "../models"
 * import { AssetRosterObject } from "../interfaces/mongoose.gen.ts"
 *
 * const assetrosterObject: AssetRosterObject = assetroster.toObject();
 * ```
 */
export type AssetRosterObject = AssetRoster;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type AssetRosterQuery = mongoose.Query<
  any,
  AssetRosterDocument,
  AssetRosterQueries
> &
  AssetRosterQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `AssetRosterSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type AssetRosterQueries = {
  paginate: (this: AssetRosterQuery, ...args: any[]) => AssetRosterQuery;
};

export type AssetRosterMethods = {};

export type AssetRosterStatics = {
  paginate: (this: AssetRosterModel, ...args: any[]) => any;
  paginateSubDocs: (this: AssetRosterModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetRoster = mongoose.model<AssetRosterDocument, AssetRosterModel>("AssetRoster", AssetRosterSchema);
 * ```
 */
export type AssetRosterModel = mongoose.Model<
  AssetRosterDocument,
  AssetRosterQueries
> &
  AssetRosterStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new AssetRoster schema instances:
 * ```
 * const AssetRosterSchema: AssetRosterSchema = new mongoose.Schema({ ... })
 * ```
 */
export type AssetRosterSchema = mongoose.Schema<
  AssetRosterDocument,
  AssetRosterModel,
  AssetRosterMethods,
  AssetRosterQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `AssetRosterDocument["attachments"]` element.
 */
export type AssetRosterAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetRoster = mongoose.model<AssetRosterDocument, AssetRosterModel>("AssetRoster", AssetRosterSchema);
 * ```
 */
export type AssetRosterDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  AssetRosterQueries
> &
  AssetRosterMethods & {
    assetTypeIds: mongoose.Types.Array<AssetTypeDocument>;
    vendorIds?: mongoose.Types.Array<ContactDocument>;
    makeIds: mongoose.Types.Array<ContactDocument>;
    productModel: string;
    serialNumber: string;
    acquiredDate: Date;
    acquiredPrice?: number;
    currentPrice?: number;
    condition?: "excellent" | "good" | "fair" | "poor";
    maintenanceWindowIds: mongoose.Types.Array<MaintenanceWindowDocument>;
    photo?: mongoose.Types.ObjectId;
    locationId?: RoomDocument;
    warrantyDate?: Date;
    remarks?: string;
    status?:
      | "active"
      | "awaiting-commissioning"
      | "under-service"
      | "decommissioned"
      | "in-pm";
    minMaintenanceDate?: Date;
    maintenanceDate?: Date;
    maxMaintenanceDate?: Date;
    attachments: mongoose.Types.DocumentArray<AssetRosterAttachmentDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    assetCommission: any;
    assetMaintenances: any;
  };

/**
 * Lean version of AssetTypeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AssetTypeDocument.toObject()`. To avoid conflicts with model names, use the type alias `AssetTypeObject`.
 * ```
 * const assettypeObject = assettype.toObject();
 * ```
 */
export type AssetType = {
  name: string;
  description?: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of AssetTypeDocument (type alias of `AssetType`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { AssetType } from "../models"
 * import { AssetTypeObject } from "../interfaces/mongoose.gen.ts"
 *
 * const assettypeObject: AssetTypeObject = assettype.toObject();
 * ```
 */
export type AssetTypeObject = AssetType;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type AssetTypeQuery = mongoose.Query<
  any,
  AssetTypeDocument,
  AssetTypeQueries
> &
  AssetTypeQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `AssetTypeSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type AssetTypeQueries = {
  paginate: (this: AssetTypeQuery, ...args: any[]) => AssetTypeQuery;
};

export type AssetTypeMethods = {};

export type AssetTypeStatics = {
  paginate: (this: AssetTypeModel, ...args: any[]) => any;
  paginateSubDocs: (this: AssetTypeModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetType = mongoose.model<AssetTypeDocument, AssetTypeModel>("AssetType", AssetTypeSchema);
 * ```
 */
export type AssetTypeModel = mongoose.Model<
  AssetTypeDocument,
  AssetTypeQueries
> &
  AssetTypeStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new AssetType schema instances:
 * ```
 * const AssetTypeSchema: AssetTypeSchema = new mongoose.Schema({ ... })
 * ```
 */
export type AssetTypeSchema = mongoose.Schema<
  AssetTypeDocument,
  AssetTypeModel,
  AssetTypeMethods,
  AssetTypeQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const AssetType = mongoose.model<AssetTypeDocument, AssetTypeModel>("AssetType", AssetTypeSchema);
 * ```
 */
export type AssetTypeDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  AssetTypeQueries
> &
  AssetTypeMethods & {
    name: string;
    description?: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of BCDSupplierDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDSupplier = {
  contactId: Contact;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDImporterDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDImporter = {
  contactId: Contact;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDTransportDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDTransport = {
  type: "AIRLINE" | "VESSEL";
  aircraftOrVessel: string;
  flightOrVoyage: string;
  port: string;
  arrivalDate: Date;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDChargeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDCharge = {
  code: "212" | "641" | "640";
  percentage?: number;
  amount: number;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDAdditionalInformationDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDAdditionalInformation = {
  type: "TXT" | "INV" | "SUP";
  value: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDOgdDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDOgd = {
  paymentCode?: string;
  costCode: string;
  objectCode: string;
  subsidiaryCode: string;
  explanation?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDDeclarantDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDDeclarant = {
  name: string;
  companyId: string;
  date: Date;
  capacity: string;
  traderReference: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDRecordChargeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDRecordDocument.toObject()`.
 * ```
 * const bcdrecordObject = bcdrecord.toObject();
 * ```
 */
export type BCDRecordCharge = {
  code: "212" | "641" | "640";
  percentage?: number;
  amount: number;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDRecordTaxDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDRecordDocument.toObject()`.
 * ```
 * const bcdrecordObject = bcdrecord.toObject();
 * ```
 */
export type BCDRecordTax = {
  type: "CUD" | "WHA" | "WSF";
  taxId: "F" | "E";
  valueForTax: number;
  ratePercentage: number;
  amount: number;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDRecordAdditionalInformationDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDRecordDocument.toObject()`.
 * ```
 * const bcdrecordObject = bcdrecord.toObject();
 * ```
 */
export type BCDRecordAdditionalInformation = {
  type: "TXT" | "INV" | "SUP";
  value: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDRecordDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDRecord = {
  number: number;
  cpc: string;
  origin: Country;
  tariff: string;
  description: string;
  quantity: number;
  quantityTwo?: number;
  supplementaryCode: string;
  currency: string;
  linesSubtotal?: number;
  exchangeRate?: number;
  charges: BCDRecordCharge[];
  tax: BCDRecordTax[];
  additionalInformation: BCDRecordAdditionalInformation[];
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDEbcdFileDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDEbcdDocument.toObject()`.
 * ```
 * const bcdebcdObject = bcdebcd.toObject();
 * ```
 */
export type BCDEbcdFile = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of BCDEbcdDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCDEbcd = {
  file: BCDEbcdFile;
  type:
    | "SENT_CSV"
    | "FILE_ERROR_CSV"
    | "FORMAT_ERROR_PDF"
    | "FORMAT_ERROR_TXT"
    | "RELEASE_CSV"
    | "RELEASE_PDF"
    | "RELEASE_TXT"
    | "RECEIPT_TXT";
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of BCDDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BCDDocument.toObject()`. To avoid conflicts with model names, use the type alias `BCDObject`.
 * ```
 * const bcdObject = bcd.toObject();
 * ```
 */
export type BCD = {
  shippingId: Shipping;
  status?:
    | "DRAFT"
    | "PENDING_RESPONSE"
    | "FAILED"
    | "PENDING_QUERY"
    | "SUBMITTED";
  type: "I" | "E" | "D" | "A";
  supplier: BCDSupplier;
  importer: BCDImporter;
  transport: BCDTransport;
  manifest: string;
  masterBOLAWB: string;
  directShipmentCountry: Country;
  originalShipmentCountry: Country;
  warehouseId?: string;
  charges: BCDCharge[];
  containerIds: string[];
  houseBOLAWBs: string[];
  valuationMethod: "01" | "02";
  packagesCount: number;
  additionalInformation: BCDAdditionalInformation[];
  ogd: BCDOgd;
  paymentAccounts: string[];
  declarant: BCDDeclarant;
  records: BCDRecord[];
  ebcds: BCDEbcd[];
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of BCDDocument (type alias of `BCD`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { BCD } from "../models"
 * import { BCDObject } from "../interfaces/mongoose.gen.ts"
 *
 * const bcdObject: BCDObject = bcd.toObject();
 * ```
 */
export type BCDObject = BCD;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type BCDQuery = mongoose.Query<any, BCDDocument, BCDQueries> &
  BCDQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `BCDSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type BCDQueries = {
  paginate: (this: BCDQuery, ...args: any[]) => BCDQuery;
};

export type BCDMethods = {};

export type BCDStatics = {
  paginate: (this: BCDModel, ...args: any[]) => any;
  paginateSubDocs: (this: BCDModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDModel = mongoose.Model<BCDDocument, BCDQueries> & BCDStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new BCD schema instances:
 * ```
 * const BCDSchema: BCDSchema = new mongoose.Schema({ ... })
 * ```
 */
export type BCDSchema = mongoose.Schema<
  BCDDocument,
  BCDModel,
  BCDMethods,
  BCDQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDSupplierDocument = mongoose.Document<mongoose.Types.ObjectId> & {
  contactId: ContactDocument;
  _id: mongoose.Types.ObjectId;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDImporterDocument = mongoose.Document<mongoose.Types.ObjectId> & {
  contactId: ContactDocument;
  _id: mongoose.Types.ObjectId;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDTransportDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    type: "AIRLINE" | "VESSEL";
    aircraftOrVessel: string;
    flightOrVoyage: string;
    port: string;
    arrivalDate: Date;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDDocument["charges"]` element.
 */
export type BCDChargeDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    code: "212" | "641" | "640";
    percentage?: number;
    amount: number;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDDocument["additionalInformation"]` element.
 */
export type BCDAdditionalInformationDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    type: "TXT" | "INV" | "SUP";
    value: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDOgdDocument = mongoose.Document<mongoose.Types.ObjectId> & {
  paymentCode?: string;
  costCode: string;
  objectCode: string;
  subsidiaryCode: string;
  explanation?: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDDeclarantDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    name: string;
    companyId: string;
    date: Date;
    capacity: string;
    traderReference: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDRecordDocument["charges"]` element.
 */
export type BCDRecordChargeDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    code: "212" | "641" | "640";
    percentage?: number;
    amount: number;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDRecordDocument["tax"]` element.
 */
export type BCDRecordTaxDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    type: "CUD" | "WHA" | "WSF";
    taxId: "F" | "E";
    valueForTax: number;
    ratePercentage: number;
    amount: number;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDRecordDocument["additionalInformation"]` element.
 */
export type BCDRecordAdditionalInformationDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    type: "TXT" | "INV" | "SUP";
    value: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDDocument["records"]` element.
 */
export type BCDRecordDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    number: number;
    cpc: string;
    origin: CountryDocument;
    tariff: string;
    description: string;
    quantity: number;
    quantityTwo?: number;
    supplementaryCode: string;
    currency: string;
    linesSubtotal?: number;
    exchangeRate?: number;
    charges: mongoose.Types.DocumentArray<BCDRecordChargeDocument>;
    tax: mongoose.Types.DocumentArray<BCDRecordTaxDocument>;
    additionalInformation: mongoose.Types.DocumentArray<BCDRecordAdditionalInformationDocument>;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCDEbcd = mongoose.model<BCDEbcdDocument, BCDEbcdModel>("BCDEbcd", BCDEbcdSchema);
 * ```
 */
export type BCDEbcdFileDocument = mongoose.Document<mongoose.Types.ObjectId> & {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Mongoose Subdocument type
 *
 * Type of `BCDDocument["ebcds"]` element.
 */
export type BCDEbcdDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    file: BCDEbcdFileDocument;
    type:
      | "SENT_CSV"
      | "FILE_ERROR_CSV"
      | "FORMAT_ERROR_PDF"
      | "FORMAT_ERROR_TXT"
      | "RELEASE_CSV"
      | "RELEASE_PDF"
      | "RELEASE_TXT"
      | "RECEIPT_TXT";
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const BCD = mongoose.model<BCDDocument, BCDModel>("BCD", BCDSchema);
 * ```
 */
export type BCDDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  BCDQueries
> &
  BCDMethods & {
    shippingId: ShippingDocument;
    status?:
      | "DRAFT"
      | "PENDING_RESPONSE"
      | "FAILED"
      | "PENDING_QUERY"
      | "SUBMITTED";
    type: "I" | "E" | "D" | "A";
    supplier: BCDSupplierDocument;
    importer: BCDImporterDocument;
    transport: BCDTransportDocument;
    manifest: string;
    masterBOLAWB: string;
    directShipmentCountry: CountryDocument;
    originalShipmentCountry: CountryDocument;
    warehouseId?: string;
    charges: mongoose.Types.DocumentArray<BCDChargeDocument>;
    containerIds: mongoose.Types.Array<string>;
    houseBOLAWBs: mongoose.Types.Array<string>;
    valuationMethod: "01" | "02";
    packagesCount: number;
    additionalInformation: mongoose.Types.DocumentArray<BCDAdditionalInformationDocument>;
    ogd: BCDOgdDocument;
    paymentAccounts: mongoose.Types.Array<string>;
    declarant: BCDDeclarantDocument;
    records: mongoose.Types.DocumentArray<BCDRecordDocument>;
    ebcds: mongoose.Types.DocumentArray<BCDEbcdDocument>;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of CompanyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CompanyDocument.toObject()`. To avoid conflicts with model names, use the type alias `CompanyObject`.
 * ```
 * const companyObject = company.toObject();
 * ```
 */
export type Company = {
  name: string;
  countryId: Country;
  address: string;
  contactId: Contact;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CompanyDocument (type alias of `Company`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Company } from "../models"
 * import { CompanyObject } from "../interfaces/mongoose.gen.ts"
 *
 * const companyObject: CompanyObject = company.toObject();
 * ```
 */
export type CompanyObject = Company;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CompanyQuery = mongoose.Query<
  any,
  CompanyDocument,
  CompanyQueries
> &
  CompanyQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CompanySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CompanyQueries = {
  paginate: (this: CompanyQuery, ...args: any[]) => CompanyQuery;
};

export type CompanyMethods = {};

export type CompanyStatics = {
  paginate: (this: CompanyModel, ...args: any[]) => any;
  paginateSubDocs: (this: CompanyModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Company = mongoose.model<CompanyDocument, CompanyModel>("Company", CompanySchema);
 * ```
 */
export type CompanyModel = mongoose.Model<CompanyDocument, CompanyQueries> &
  CompanyStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Company schema instances:
 * ```
 * const CompanySchema: CompanySchema = new mongoose.Schema({ ... })
 * ```
 */
export type CompanySchema = mongoose.Schema<
  CompanyDocument,
  CompanyModel,
  CompanyMethods,
  CompanyQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Company = mongoose.model<CompanyDocument, CompanyModel>("Company", CompanySchema);
 * ```
 */
export type CompanyDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CompanyQueries
> &
  CompanyMethods & {
    name: string;
    countryId: CountryDocument;
    address: string;
    contactId: ContactDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ContactDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContactDocument.toObject()`. To avoid conflicts with model names, use the type alias `ContactObject`.
 * ```
 * const contactObject = contact.toObject();
 * ```
 */
export type Contact = {
  name: string;
  lastName?: string;
  phoneNumber?: string;
  email?: string;
  website?: string;
  parentId?: Contact;
  type: "individual" | "company";
  countryId?: Country;
  state?: string;
  city?: string;
  zipCode?: string;
  streetAddress?: string;
  streetAddress2?: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  childIds: any;
  fullName: string;
  fullAddress: string;
};

/**
 * Lean version of ContactDocument (type alias of `Contact`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Contact } from "../models"
 * import { ContactObject } from "../interfaces/mongoose.gen.ts"
 *
 * const contactObject: ContactObject = contact.toObject();
 * ```
 */
export type ContactObject = Contact;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ContactQuery = mongoose.Query<
  any,
  ContactDocument,
  ContactQueries
> &
  ContactQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ContactSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ContactQueries = {
  paginate: (this: ContactQuery, ...args: any[]) => ContactQuery;
};

export type ContactMethods = {};

export type ContactStatics = {
  paginate: (this: ContactModel, ...args: any[]) => any;
  paginateSubDocs: (this: ContactModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Contact = mongoose.model<ContactDocument, ContactModel>("Contact", ContactSchema);
 * ```
 */
export type ContactModel = mongoose.Model<ContactDocument, ContactQueries> &
  ContactStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Contact schema instances:
 * ```
 * const ContactSchema: ContactSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ContactSchema = mongoose.Schema<
  ContactDocument,
  ContactModel,
  ContactMethods,
  ContactQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Contact = mongoose.model<ContactDocument, ContactModel>("Contact", ContactSchema);
 * ```
 */
export type ContactDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ContactQueries
> &
  ContactMethods & {
    name: string;
    lastName?: string;
    phoneNumber?: string;
    email?: string;
    website?: string;
    parentId?: ContactDocument;
    type: "individual" | "company";
    countryId?: CountryDocument;
    state?: string;
    city?: string;
    zipCode?: string;
    streetAddress?: string;
    streetAddress2?: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    childIds: any;
    fullName: string;
    fullAddress: string;
  };

/**
 * Lean version of CountryDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CountryDocument.toObject()`. To avoid conflicts with model names, use the type alias `CountryObject`.
 * ```
 * const countryObject = country.toObject();
 * ```
 */
export type Country = {
  name: string;
  code: string;
  currencyCode: string;
  currencySymbol: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CountryDocument (type alias of `Country`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Country } from "../models"
 * import { CountryObject } from "../interfaces/mongoose.gen.ts"
 *
 * const countryObject: CountryObject = country.toObject();
 * ```
 */
export type CountryObject = Country;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CountryQuery = mongoose.Query<
  any,
  CountryDocument,
  CountryQueries
> &
  CountryQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CountrySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CountryQueries = {
  paginate: (this: CountryQuery, ...args: any[]) => CountryQuery;
};

export type CountryMethods = {};

export type CountryStatics = {
  paginate: (this: CountryModel, ...args: any[]) => any;
  paginateSubDocs: (this: CountryModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Country = mongoose.model<CountryDocument, CountryModel>("Country", CountrySchema);
 * ```
 */
export type CountryModel = mongoose.Model<CountryDocument, CountryQueries> &
  CountryStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Country schema instances:
 * ```
 * const CountrySchema: CountrySchema = new mongoose.Schema({ ... })
 * ```
 */
export type CountrySchema = mongoose.Schema<
  CountryDocument,
  CountryModel,
  CountryMethods,
  CountryQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Country = mongoose.model<CountryDocument, CountryModel>("Country", CountrySchema);
 * ```
 */
export type CountryDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CountryQueries
> &
  CountryMethods & {
    name: string;
    code: string;
    currencyCode: string;
    currencySymbol: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of CRMDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CRMDocument.toObject()`. To avoid conflicts with model names, use the type alias `CRMObject`.
 * ```
 * const crmObject = crm.toObject();
 * ```
 */
export type CRM = {
  title: string;
  amount: number;
  currency?: string;
  stage?:
    | "prospecting"
    | "qualification"
    | "proposal"
    | "negotiation"
    | "closed-won"
    | "closed-lost";
  probability?: number;
  expectedCloseDate?: Date;
  actualCloseDate?: Date;
  contact: Contact;
  company: Company;
  owner?: User;
  description?: string;
  notes?: string;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CRMDocument (type alias of `CRM`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { CRM } from "../models"
 * import { CRMObject } from "../interfaces/mongoose.gen.ts"
 *
 * const crmObject: CRMObject = crm.toObject();
 * ```
 */
export type CRMObject = CRM;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CRMQuery = mongoose.Query<any, CRMDocument, CRMQueries> &
  CRMQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CRMSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CRMQueries = {
  paginate: (this: CRMQuery, ...args: any[]) => CRMQuery;
};

export type CRMMethods = {};

export type CRMStatics = {
  paginate: (this: CRMModel, ...args: any[]) => any;
  paginateSubDocs: (this: CRMModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CRM = mongoose.model<CRMDocument, CRMModel>("CRM", CRMSchema);
 * ```
 */
export type CRMModel = mongoose.Model<CRMDocument, CRMQueries> & CRMStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new CRM schema instances:
 * ```
 * const CRMSchema: CRMSchema = new mongoose.Schema({ ... })
 * ```
 */
export type CRMSchema = mongoose.Schema<
  CRMDocument,
  CRMModel,
  CRMMethods,
  CRMQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CRM = mongoose.model<CRMDocument, CRMModel>("CRM", CRMSchema);
 * ```
 */
export type CRMDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CRMQueries
> &
  CRMMethods & {
    title: string;
    amount: number;
    currency?: string;
    stage?:
      | "prospecting"
      | "qualification"
      | "proposal"
      | "negotiation"
      | "closed-won"
      | "closed-lost";
    probability?: number;
    expectedCloseDate?: Date;
    actualCloseDate?: Date;
    contact: ContactDocument;
    company: CompanyDocument;
    owner?: UserDocument;
    description?: string;
    notes?: string;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of FacilityDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `FacilityDocument.toObject()`. To avoid conflicts with model names, use the type alias `FacilityObject`.
 * ```
 * const facilityObject = facility.toObject();
 * ```
 */
export type Facility = {
  name: string;
  contactId?: Contact;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  rooms: any;
};

/**
 * Lean version of FacilityDocument (type alias of `Facility`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Facility } from "../models"
 * import { FacilityObject } from "../interfaces/mongoose.gen.ts"
 *
 * const facilityObject: FacilityObject = facility.toObject();
 * ```
 */
export type FacilityObject = Facility;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type FacilityQuery = mongoose.Query<
  any,
  FacilityDocument,
  FacilityQueries
> &
  FacilityQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `FacilitySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type FacilityQueries = {
  paginate: (this: FacilityQuery, ...args: any[]) => FacilityQuery;
};

export type FacilityMethods = {};

export type FacilityStatics = {
  paginate: (this: FacilityModel, ...args: any[]) => any;
  paginateSubDocs: (this: FacilityModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Facility = mongoose.model<FacilityDocument, FacilityModel>("Facility", FacilitySchema);
 * ```
 */
export type FacilityModel = mongoose.Model<FacilityDocument, FacilityQueries> &
  FacilityStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Facility schema instances:
 * ```
 * const FacilitySchema: FacilitySchema = new mongoose.Schema({ ... })
 * ```
 */
export type FacilitySchema = mongoose.Schema<
  FacilityDocument,
  FacilityModel,
  FacilityMethods,
  FacilityQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Facility = mongoose.model<FacilityDocument, FacilityModel>("Facility", FacilitySchema);
 * ```
 */
export type FacilityDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  FacilityQueries
> &
  FacilityMethods & {
    name: string;
    contactId?: ContactDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    rooms: any;
  };

/**
 * Lean version of RoomDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoomDocument.toObject()`. To avoid conflicts with model names, use the type alias `RoomObject`.
 * ```
 * const roomObject = room.toObject();
 * ```
 */
export type Room = {
  name: string;
  code: string;
  address: string;
  facilityId: Facility;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of RoomDocument (type alias of `Room`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Room } from "../models"
 * import { RoomObject } from "../interfaces/mongoose.gen.ts"
 *
 * const roomObject: RoomObject = room.toObject();
 * ```
 */
export type RoomObject = Room;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type RoomQuery = mongoose.Query<any, RoomDocument, RoomQueries> &
  RoomQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `RoomSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type RoomQueries = {
  paginate: (this: RoomQuery, ...args: any[]) => RoomQuery;
};

export type RoomMethods = {};

export type RoomStatics = {
  paginate: (this: RoomModel, ...args: any[]) => any;
  paginateSubDocs: (this: RoomModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Room = mongoose.model<RoomDocument, RoomModel>("Room", RoomSchema);
 * ```
 */
export type RoomModel = mongoose.Model<RoomDocument, RoomQueries> & RoomStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Room schema instances:
 * ```
 * const RoomSchema: RoomSchema = new mongoose.Schema({ ... })
 * ```
 */
export type RoomSchema = mongoose.Schema<
  RoomDocument,
  RoomModel,
  RoomMethods,
  RoomQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Room = mongoose.model<RoomDocument, RoomModel>("Room", RoomSchema);
 * ```
 */
export type RoomDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  RoomQueries
> &
  RoomMethods & {
    name: string;
    code: string;
    address: string;
    facilityId: FacilityDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of MaintenanceWindowDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `MaintenanceWindowDocument.toObject()`. To avoid conflicts with model names, use the type alias `MaintenanceWindowObject`.
 * ```
 * const maintenancewindowObject = maintenancewindow.toObject();
 * ```
 */
export type MaintenanceWindow = {
  name: string;
  daysBefore: number;
  daysAfter: number;
  recurrency:
    | "daily"
    | "weekly"
    | "monthly"
    | "quarterly"
    | "semi-anually"
    | "annually";
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of MaintenanceWindowDocument (type alias of `MaintenanceWindow`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { MaintenanceWindow } from "../models"
 * import { MaintenanceWindowObject } from "../interfaces/mongoose.gen.ts"
 *
 * const maintenancewindowObject: MaintenanceWindowObject = maintenancewindow.toObject();
 * ```
 */
export type MaintenanceWindowObject = MaintenanceWindow;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type MaintenanceWindowQuery = mongoose.Query<
  any,
  MaintenanceWindowDocument,
  MaintenanceWindowQueries
> &
  MaintenanceWindowQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `MaintenanceWindowSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type MaintenanceWindowQueries = {
  paginate: (
    this: MaintenanceWindowQuery,
    ...args: any[]
  ) => MaintenanceWindowQuery;
};

export type MaintenanceWindowMethods = {
  parseRecurrencyForDayjs: (
    this: MaintenanceWindowDocument,
    ...args: any[]
  ) => any;
};

export type MaintenanceWindowStatics = {
  paginate: (this: MaintenanceWindowModel, ...args: any[]) => any;
  paginateSubDocs: (this: MaintenanceWindowModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const MaintenanceWindow = mongoose.model<MaintenanceWindowDocument, MaintenanceWindowModel>("MaintenanceWindow", MaintenanceWindowSchema);
 * ```
 */
export type MaintenanceWindowModel = mongoose.Model<
  MaintenanceWindowDocument,
  MaintenanceWindowQueries
> &
  MaintenanceWindowStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new MaintenanceWindow schema instances:
 * ```
 * const MaintenanceWindowSchema: MaintenanceWindowSchema = new mongoose.Schema({ ... })
 * ```
 */
export type MaintenanceWindowSchema = mongoose.Schema<
  MaintenanceWindowDocument,
  MaintenanceWindowModel,
  MaintenanceWindowMethods,
  MaintenanceWindowQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const MaintenanceWindow = mongoose.model<MaintenanceWindowDocument, MaintenanceWindowModel>("MaintenanceWindow", MaintenanceWindowSchema);
 * ```
 */
export type MaintenanceWindowDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  MaintenanceWindowQueries
> &
  MaintenanceWindowMethods & {
    name: string;
    daysBefore: number;
    daysAfter: number;
    recurrency:
      | "daily"
      | "weekly"
      | "monthly"
      | "quarterly"
      | "semi-anually"
      | "annually";
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ProjectDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProjectDocument.toObject()`. To avoid conflicts with model names, use the type alias `ProjectObject`.
 * ```
 * const projectObject = project.toObject();
 * ```
 */
export type Project = {
  name: string;
  description?: string;
  createdBy: User;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProjectDocument (type alias of `Project`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Project } from "../models"
 * import { ProjectObject } from "../interfaces/mongoose.gen.ts"
 *
 * const projectObject: ProjectObject = project.toObject();
 * ```
 */
export type ProjectObject = Project;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ProjectQuery = mongoose.Query<
  any,
  ProjectDocument,
  ProjectQueries
> &
  ProjectQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ProjectSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ProjectQueries = {
  paginate: (this: ProjectQuery, ...args: any[]) => ProjectQuery;
};

export type ProjectMethods = {};

export type ProjectStatics = {
  paginate: (this: ProjectModel, ...args: any[]) => any;
  paginateSubDocs: (this: ProjectModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Project = mongoose.model<ProjectDocument, ProjectModel>("Project", ProjectSchema);
 * ```
 */
export type ProjectModel = mongoose.Model<ProjectDocument, ProjectQueries> &
  ProjectStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Project schema instances:
 * ```
 * const ProjectSchema: ProjectSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ProjectSchema = mongoose.Schema<
  ProjectDocument,
  ProjectModel,
  ProjectMethods,
  ProjectQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Project = mongoose.model<ProjectDocument, ProjectModel>("Project", ProjectSchema);
 * ```
 */
export type ProjectDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ProjectQueries
> &
  ProjectMethods & {
    name: string;
    description?: string;
    createdBy: UserDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ReportingDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ReportingDocument.toObject()`. To avoid conflicts with model names, use the type alias `ReportingObject`.
 * ```
 * const reportingObject = reporting.toObject();
 * ```
 */
export type Reporting = {
  title: string;
  template: string;
  model: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ReportingDocument (type alias of `Reporting`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Reporting } from "../models"
 * import { ReportingObject } from "../interfaces/mongoose.gen.ts"
 *
 * const reportingObject: ReportingObject = reporting.toObject();
 * ```
 */
export type ReportingObject = Reporting;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ReportingQuery = mongoose.Query<
  any,
  ReportingDocument,
  ReportingQueries
> &
  ReportingQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ReportingSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ReportingQueries = {
  paginate: (this: ReportingQuery, ...args: any[]) => ReportingQuery;
};

export type ReportingMethods = {};

export type ReportingStatics = {
  paginate: (this: ReportingModel, ...args: any[]) => any;
  paginateSubDocs: (this: ReportingModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Reporting = mongoose.model<ReportingDocument, ReportingModel>("Reporting", ReportingSchema);
 * ```
 */
export type ReportingModel = mongoose.Model<
  ReportingDocument,
  ReportingQueries
> &
  ReportingStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Reporting schema instances:
 * ```
 * const ReportingSchema: ReportingSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ReportingSchema = mongoose.Schema<
  ReportingDocument,
  ReportingModel,
  ReportingMethods,
  ReportingQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Reporting = mongoose.model<ReportingDocument, ReportingModel>("Reporting", ReportingSchema);
 * ```
 */
export type ReportingDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ReportingQueries
> &
  ReportingMethods & {
    title: string;
    template: string;
    model: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of PolicyConditionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `PolicyDocument.toObject()`.
 * ```
 * const policyObject = policy.toObject();
 * ```
 */
export type PolicyCondition = {
  key: string;
  operator: "==" | "!=" | ">" | "<" | "in";
  value: any;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of PolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `PolicyDocument.toObject()`. To avoid conflicts with model names, use the type alias `PolicyObject`.
 * ```
 * const policyObject = policy.toObject();
 * ```
 */
export type Policy = {
  name: string;
  resource: string;
  type: "view" | "menu" | "model";
  conditions: PolicyCondition[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of PolicyDocument (type alias of `Policy`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Policy } from "../models"
 * import { PolicyObject } from "../interfaces/mongoose.gen.ts"
 *
 * const policyObject: PolicyObject = policy.toObject();
 * ```
 */
export type PolicyObject = Policy;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type PolicyQuery = mongoose.Query<any, PolicyDocument, PolicyQueries> &
  PolicyQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `PolicySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type PolicyQueries = {
  paginate: (this: PolicyQuery, ...args: any[]) => PolicyQuery;
};

export type PolicyMethods = {};

export type PolicyStatics = {
  paginate: (this: PolicyModel, ...args: any[]) => any;
  paginateSubDocs: (this: PolicyModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Policy = mongoose.model<PolicyDocument, PolicyModel>("Policy", PolicySchema);
 * ```
 */
export type PolicyModel = mongoose.Model<PolicyDocument, PolicyQueries> &
  PolicyStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Policy schema instances:
 * ```
 * const PolicySchema: PolicySchema = new mongoose.Schema({ ... })
 * ```
 */
export type PolicySchema = mongoose.Schema<
  PolicyDocument,
  PolicyModel,
  PolicyMethods,
  PolicyQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `PolicyDocument["conditions"]` element.
 */
export type PolicyConditionDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    key: string;
    operator: "==" | "!=" | ">" | "<" | "in";
    value: any;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Policy = mongoose.model<PolicyDocument, PolicyModel>("Policy", PolicySchema);
 * ```
 */
export type PolicyDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  PolicyQueries
> &
  PolicyMethods & {
    name: string;
    resource: string;
    type: "view" | "menu" | "model";
    conditions: mongoose.Types.DocumentArray<PolicyConditionDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of RolePolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoleDocument.toObject()`.
 * ```
 * const roleObject = role.toObject();
 * ```
 */
export type RolePolicy = {
  policyId: Policy;
  actions: ("create" | "read" | "update" | "delete")[];
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of RoleDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoleDocument.toObject()`. To avoid conflicts with model names, use the type alias `RoleObject`.
 * ```
 * const roleObject = role.toObject();
 * ```
 */
export type Role = {
  name: string;
  policies: RolePolicy[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of RoleDocument (type alias of `Role`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Role } from "../models"
 * import { RoleObject } from "../interfaces/mongoose.gen.ts"
 *
 * const roleObject: RoleObject = role.toObject();
 * ```
 */
export type RoleObject = Role;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type RoleQuery = mongoose.Query<any, RoleDocument, RoleQueries> &
  RoleQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `RoleSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type RoleQueries = {
  paginate: (this: RoleQuery, ...args: any[]) => RoleQuery;
};

export type RoleMethods = {};

export type RoleStatics = {
  paginate: (this: RoleModel, ...args: any[]) => any;
  paginateSubDocs: (this: RoleModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Role = mongoose.model<RoleDocument, RoleModel>("Role", RoleSchema);
 * ```
 */
export type RoleModel = mongoose.Model<RoleDocument, RoleQueries> & RoleStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Role schema instances:
 * ```
 * const RoleSchema: RoleSchema = new mongoose.Schema({ ... })
 * ```
 */
export type RoleSchema = mongoose.Schema<
  RoleDocument,
  RoleModel,
  RoleMethods,
  RoleQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `RoleDocument["policies"]` element.
 */
export type RolePolicyDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    policyId: PolicyDocument;
    actions: mongoose.Types.Array<"create" | "read" | "update" | "delete">;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Role = mongoose.model<RoleDocument, RoleModel>("Role", RoleSchema);
 * ```
 */
export type RoleDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  RoleQueries
> &
  RoleMethods & {
    name: string;
    policies: mongoose.Types.DocumentArray<RolePolicyDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ShippingInvoiceCommentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingInvoiceDocument.toObject()`.
 * ```
 * const shippinginvoiceObject = shippinginvoice.toObject();
 * ```
 */
export type ShippingInvoiceComment = {
  description: string;
  createdAt?: Date;
  createdBy: User;
  active?: boolean;
  status?: "DRAFT" | "CANCELLED" | "DONE";
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ShippingInvoicePdfExtractedDatumLineTariffDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingInvoicePdfExtractedDatumLineDocument.toObject()`.
 * ```
 * const shippinginvoicepdfextracteddatumlineObject = shippinginvoicepdfextracteddatumline.toObject();
 * ```
 */
export type ShippingInvoicePdfExtractedDatumLineTariff = {
  code?: string | null;
  chapter: string;
  heading: string;
  subheading: string;
  userDescription?: string | null;
  description?: string | null;
  rateOfDuty?: number | null;
  unitOfMeasurement?: string | null;
  tax?: number | null;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ShippingInvoicePdfExtractedDatumLineDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingInvoicePdfExtractedDatumDocument.toObject()`.
 * ```
 * const shippinginvoicepdfextracteddatumObject = shippinginvoicepdfextracteddatum.toObject();
 * ```
 */
export type ShippingInvoicePdfExtractedDatumLine = {
  lineNumber: string;
  countryId: Country;
  currency?: string | null;
  description: string;
  quantity: number;
  price: number;
  subtotal: number;
  customsClassification: string;
  hsCode?: string | null;
  customsChapter?: string | null;
  customsHeading?: string | null;
  customsSubheading?: string | null;
  chapterDescription?: string | null;
  headingDescription?: string | null;
  subheadingDescription?: string | null;
  recordNumber?: number | null;
  tariff?: ShippingInvoicePdfExtractedDatumLineTariff;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ShippingInvoicePdfExtractedDatumDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingInvoicePdfDocument.toObject()`.
 * ```
 * const shippinginvoicepdfObject = shippinginvoicepdf.toObject();
 * ```
 */
export type ShippingInvoicePdfExtractedDatum = {
  header: {
    invoiceNumber: string;
    date: Date;
    countryId: Country;
    companyId?: Company;
    address?: string | null;
    phone?: string | null;
    email?: string;
    total: number;
    currency?: string | null;
  };
  lines: ShippingInvoicePdfExtractedDatumLine[];
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ShippingInvoicePdfFileDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingInvoicePdfDocument.toObject()`.
 * ```
 * const shippinginvoicepdfObject = shippinginvoicepdf.toObject();
 * ```
 */
export type ShippingInvoicePdfFile = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ShippingInvoicePdfDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingInvoiceDocument.toObject()`.
 * ```
 * const shippinginvoiceObject = shippinginvoice.toObject();
 * ```
 */
export type ShippingInvoicePdf = {
  extractedData?: ShippingInvoicePdfExtractedDatum;
  file?: ShippingInvoicePdfFile;
};

/**
 * Lean version of ShippingInvoiceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingDocument.toObject()`.
 * ```
 * const shippingObject = shipping.toObject();
 * ```
 */
export type ShippingInvoice = {
  comments: ShippingInvoiceComment[];
  pdf?: ShippingInvoicePdf;
  status: "PROCESSING_PDF" | "ERROR_JSON" | "DATA_PROCESSED" | "COMPLETE";
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ShippingDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ShippingDocument.toObject()`. To avoid conflicts with model names, use the type alias `ShippingObject`.
 * ```
 * const shippingObject = shipping.toObject();
 * ```
 */
export type Shipping = {
  name: string;
  origin: Country;
  destination: Country;
  createdBy: User;
  updatedBy?: User;
  status: "UPLOADING" | "ERROR" | "PDF_PROCESSED" | "BCD_SENT";
  stage: "HS_CODES" | "TARIFF_CODES" | "GROUPING" | "SUMMARY" | "COMPLETE";
  invoices: ShippingInvoice[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  bcds: any;
};

/**
 * Lean version of ShippingDocument (type alias of `Shipping`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Shipping } from "../models"
 * import { ShippingObject } from "../interfaces/mongoose.gen.ts"
 *
 * const shippingObject: ShippingObject = shipping.toObject();
 * ```
 */
export type ShippingObject = Shipping;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ShippingQuery = mongoose.Query<
  any,
  ShippingDocument,
  ShippingQueries
> &
  ShippingQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ShippingSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ShippingQueries = {
  paginate: (this: ShippingQuery, ...args: any[]) => ShippingQuery;
};

export type ShippingMethods = {};

export type ShippingStatics = {
  paginate: (this: ShippingModel, ...args: any[]) => any;
  paginateSubDocs: (this: ShippingModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Shipping = mongoose.model<ShippingDocument, ShippingModel>("Shipping", ShippingSchema);
 * ```
 */
export type ShippingModel = mongoose.Model<ShippingDocument, ShippingQueries> &
  ShippingStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Shipping schema instances:
 * ```
 * const ShippingSchema: ShippingSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ShippingSchema = mongoose.Schema<
  ShippingDocument,
  ShippingModel,
  ShippingMethods,
  ShippingQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `ShippingInvoiceDocument["comments"]` element.
 */
export type ShippingInvoiceCommentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    description: string;
    createdAt?: Date;
    createdBy: UserDocument;
    active?: boolean;
    status?: "DRAFT" | "CANCELLED" | "DONE";
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ShippingInvoicePdfExtractedDatumLine = mongoose.model<ShippingInvoicePdfExtractedDatumLineDocument, ShippingInvoicePdfExtractedDatumLineModel>("ShippingInvoicePdfExtractedDatumLine", ShippingInvoicePdfExtractedDatumLineSchema);
 * ```
 */
export type ShippingInvoicePdfExtractedDatumLineTariffDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    code?: string | null;
    chapter: string;
    heading: string;
    subheading: string;
    userDescription?: string | null;
    description?: string | null;
    rateOfDuty?: number | null;
    unitOfMeasurement?: string | null;
    tax?: number | null;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Subdocument type
 *
 * Type of `ShippingInvoicePdfExtractedDatumDocument["lines"]` element.
 */
export type ShippingInvoicePdfExtractedDatumLineDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    lineNumber: string;
    countryId: CountryDocument;
    currency?: string | null;
    description: string;
    quantity: number;
    price: number;
    subtotal: number;
    customsClassification: string;
    hsCode?: string | null;
    customsChapter?: string | null;
    customsHeading?: string | null;
    customsSubheading?: string | null;
    chapterDescription?: string | null;
    headingDescription?: string | null;
    subheadingDescription?: string | null;
    recordNumber?: number | null;
    tariff?: ShippingInvoicePdfExtractedDatumLineTariffDocument;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ShippingInvoicePdf = mongoose.model<ShippingInvoicePdfDocument, ShippingInvoicePdfModel>("ShippingInvoicePdf", ShippingInvoicePdfSchema);
 * ```
 */
export type ShippingInvoicePdfExtractedDatumDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    header: {
      invoiceNumber: string;
      date: Date;
      countryId: CountryDocument;
      companyId?: CompanyDocument;
      address?: string | null;
      phone?: string | null;
      email?: string;
      total: number;
      currency?: string | null;
    };
    lines: mongoose.Types.DocumentArray<ShippingInvoicePdfExtractedDatumLineDocument>;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ShippingInvoicePdf = mongoose.model<ShippingInvoicePdfDocument, ShippingInvoicePdfModel>("ShippingInvoicePdf", ShippingInvoicePdfSchema);
 * ```
 */
export type ShippingInvoicePdfFileDocument =
  mongoose.Document<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ShippingInvoice = mongoose.model<ShippingInvoiceDocument, ShippingInvoiceModel>("ShippingInvoice", ShippingInvoiceSchema);
 * ```
 */
export type ShippingInvoicePdfDocument = mongoose.Document<any> & {
  extractedData?: ShippingInvoicePdfExtractedDatumDocument;
  file?: ShippingInvoicePdfFileDocument;
};

/**
 * Mongoose Subdocument type
 *
 * Type of `ShippingDocument["invoices"]` element.
 */
export type ShippingInvoiceDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    comments: mongoose.Types.DocumentArray<ShippingInvoiceCommentDocument>;
    pdf?: ShippingInvoicePdfDocument;
    status: "PROCESSING_PDF" | "ERROR_JSON" | "DATA_PROCESSED" | "COMPLETE";
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Shipping = mongoose.model<ShippingDocument, ShippingModel>("Shipping", ShippingSchema);
 * ```
 */
export type ShippingDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ShippingQueries
> &
  ShippingMethods & {
    name: string;
    origin: CountryDocument;
    destination: CountryDocument;
    createdBy: UserDocument;
    updatedBy?: UserDocument;
    status: "UPLOADING" | "ERROR" | "PDF_PROCESSED" | "BCD_SENT";
    stage: "HS_CODES" | "TARIFF_CODES" | "GROUPING" | "SUMMARY" | "COMPLETE";
    invoices: mongoose.Types.DocumentArray<ShippingInvoiceDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    bcds: any;
  };

/**
 * Lean version of TaskStageDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TaskStageDocument.toObject()`. To avoid conflicts with model names, use the type alias `TaskStageObject`.
 * ```
 * const taskstageObject = taskstage.toObject();
 * ```
 */
export type TaskStage = {
  name: string;
  description?: string;
  isDefault?: boolean;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of TaskStageDocument (type alias of `TaskStage`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { TaskStage } from "../models"
 * import { TaskStageObject } from "../interfaces/mongoose.gen.ts"
 *
 * const taskstageObject: TaskStageObject = taskstage.toObject();
 * ```
 */
export type TaskStageObject = TaskStage;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type TaskStageQuery = mongoose.Query<
  any,
  TaskStageDocument,
  TaskStageQueries
> &
  TaskStageQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `TaskStageSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type TaskStageQueries = {
  paginate: (this: TaskStageQuery, ...args: any[]) => TaskStageQuery;
};

export type TaskStageMethods = {};

export type TaskStageStatics = {
  paginate: (this: TaskStageModel, ...args: any[]) => any;
  paginateSubDocs: (this: TaskStageModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const TaskStage = mongoose.model<TaskStageDocument, TaskStageModel>("TaskStage", TaskStageSchema);
 * ```
 */
export type TaskStageModel = mongoose.Model<
  TaskStageDocument,
  TaskStageQueries
> &
  TaskStageStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new TaskStage schema instances:
 * ```
 * const TaskStageSchema: TaskStageSchema = new mongoose.Schema({ ... })
 * ```
 */
export type TaskStageSchema = mongoose.Schema<
  TaskStageDocument,
  TaskStageModel,
  TaskStageMethods,
  TaskStageQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const TaskStage = mongoose.model<TaskStageDocument, TaskStageModel>("TaskStage", TaskStageSchema);
 * ```
 */
export type TaskStageDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  TaskStageQueries
> &
  TaskStageMethods & {
    name: string;
    description?: string;
    isDefault?: boolean;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of TaskAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TaskDocument.toObject()`.
 * ```
 * const taskObject = task.toObject();
 * ```
 */
export type TaskAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of TaskDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TaskDocument.toObject()`. To avoid conflicts with model names, use the type alias `TaskObject`.
 * ```
 * const taskObject = task.toObject();
 * ```
 */
export type Task = {
  name: string;
  description?: string;
  plannedStartDate?: Date;
  plannedEndDate?: Date;
  plannedDuration?: number;
  progress?: number;
  stage?: TaskStage;
  projectId?: Project;
  dependencyIds?: Task[];
  parentId?: Task;
  priority?: "low" | "medium" | "high" | "urgent";
  createdBy: User;
  updatedBy?: User;
  assigned?: User;
  attachments: TaskAttachment[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  childIds: any;
};

/**
 * Lean version of TaskDocument (type alias of `Task`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Task } from "../models"
 * import { TaskObject } from "../interfaces/mongoose.gen.ts"
 *
 * const taskObject: TaskObject = task.toObject();
 * ```
 */
export type TaskObject = Task;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type TaskQuery = mongoose.Query<any, TaskDocument, TaskQueries> &
  TaskQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `TaskSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type TaskQueries = {
  paginate: (this: TaskQuery, ...args: any[]) => TaskQuery;
};

export type TaskMethods = {};

export type TaskStatics = {
  paginate: (this: TaskModel, ...args: any[]) => any;
  paginateSubDocs: (this: TaskModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Task = mongoose.model<TaskDocument, TaskModel>("Task", TaskSchema);
 * ```
 */
export type TaskModel = mongoose.Model<TaskDocument, TaskQueries> & TaskStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Task schema instances:
 * ```
 * const TaskSchema: TaskSchema = new mongoose.Schema({ ... })
 * ```
 */
export type TaskSchema = mongoose.Schema<
  TaskDocument,
  TaskModel,
  TaskMethods,
  TaskQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `TaskDocument["attachments"]` element.
 */
export type TaskAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Task = mongoose.model<TaskDocument, TaskModel>("Task", TaskSchema);
 * ```
 */
export type TaskDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  TaskQueries
> &
  TaskMethods & {
    name: string;
    description?: string;
    plannedStartDate?: Date;
    plannedEndDate?: Date;
    plannedDuration?: number;
    progress?: number;
    stage?: TaskStageDocument;
    projectId?: ProjectDocument;
    dependencyIds?: mongoose.Types.Array<TaskDocument>;
    parentId?: TaskDocument;
    priority?: "low" | "medium" | "high" | "urgent";
    createdBy: UserDocument;
    updatedBy?: UserDocument;
    assigned?: UserDocument;
    attachments: mongoose.Types.DocumentArray<TaskAttachmentDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    childIds: any;
  };

/**
 * Lean version of TemplateDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TemplateDocument.toObject()`. To avoid conflicts with model names, use the type alias `TemplateObject`.
 * ```
 * const templateObject = template.toObject();
 * ```
 */
export type Template = {
  name: string;
  codeOriginal?: string;
  codeCustom?: string;
  directory: string;
  filename: string;
  mimeType:
    | "text/typescript"
    | "application/typescript"
    | "application/javascript"
    | "text/javascript"
    | "text/html"
    | "text/css";
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of TemplateDocument (type alias of `Template`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Template } from "../models"
 * import { TemplateObject } from "../interfaces/mongoose.gen.ts"
 *
 * const templateObject: TemplateObject = template.toObject();
 * ```
 */
export type TemplateObject = Template;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type TemplateQuery = mongoose.Query<
  any,
  TemplateDocument,
  TemplateQueries
> &
  TemplateQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `TemplateSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type TemplateQueries = {
  paginate: (this: TemplateQuery, ...args: any[]) => TemplateQuery;
};

export type TemplateMethods = {};

export type TemplateStatics = {
  paginate: (this: TemplateModel, ...args: any[]) => any;
  paginateSubDocs: (this: TemplateModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Template = mongoose.model<TemplateDocument, TemplateModel>("Template", TemplateSchema);
 * ```
 */
export type TemplateModel = mongoose.Model<TemplateDocument, TemplateQueries> &
  TemplateStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Template schema instances:
 * ```
 * const TemplateSchema: TemplateSchema = new mongoose.Schema({ ... })
 * ```
 */
export type TemplateSchema = mongoose.Schema<
  TemplateDocument,
  TemplateModel,
  TemplateMethods,
  TemplateQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Template = mongoose.model<TemplateDocument, TemplateModel>("Template", TemplateSchema);
 * ```
 */
export type TemplateDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  TemplateQueries
> &
  TemplateMethods & {
    name: string;
    codeOriginal?: string;
    codeCustom?: string;
    directory: string;
    filename: string;
    mimeType:
      | "text/typescript"
      | "application/typescript"
      | "application/javascript"
      | "text/javascript"
      | "text/html"
      | "text/css";
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of UserDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`. To avoid conflicts with model names, use the type alias `UserObject`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type User = {
  authId: string;
  provider: "google.com" | "password";
  username: string;
  email: string;
  picture?: string;
  uploadedPictureId?: mongoose.Types.ObjectId;
  active?: boolean;
  roles: Role[];
  contactId?: Contact;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of UserDocument (type alias of `User`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { User } from "../models"
 * import { UserObject } from "../interfaces/mongoose.gen.ts"
 *
 * const userObject: UserObject = user.toObject();
 * ```
 */
export type UserObject = User;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type UserQuery = mongoose.Query<any, UserDocument, UserQueries> &
  UserQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `UserSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type UserQueries = {
  paginate: (this: UserQuery, ...args: any[]) => UserQuery;
};

export type UserMethods = {};

export type UserStatics = {
  paginate: (this: UserModel, ...args: any[]) => any;
  paginateSubDocs: (this: UserModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserModel = mongoose.Model<UserDocument, UserQueries> & UserStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new User schema instances:
 * ```
 * const UserSchema: UserSchema = new mongoose.Schema({ ... })
 * ```
 */
export type UserSchema = mongoose.Schema<
  UserDocument,
  UserModel,
  UserMethods,
  UserQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  UserQueries
> &
  UserMethods & {
    authId: string;
    provider: "google.com" | "password";
    username: string;
    email: string;
    picture?: string;
    uploadedPictureId?: mongoose.Types.ObjectId;
    active?: boolean;
    roles: mongoose.Types.Array<RoleDocument>;
    contactId?: ContactDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<
        infer U
      >
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module "mongoose" {
  interface Query<ResultType, DocType, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}
