/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from "mongoose";

/**
 * Lean version of ActivityHistoryDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ActivityHistoryDocument.toObject()`. To avoid conflicts with model names, use the type alias `ActivityHistoryObject`.
 * ```
 * const activityhistoryObject = activityhistory.toObject();
 * ```
 */
export type ActivityHistory = {
  title: string;
  details?: string;
  performDate: Date;
  model: string;
  modelId: mongoose.Types.ObjectId;
  metadata?: any | null;
  userId?: User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ActivityHistoryDocument (type alias of `ActivityHistory`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { ActivityHistory } from "../models"
 * import { ActivityHistoryObject } from "../interfaces/mongoose.gen.ts"
 *
 * const activityhistoryObject: ActivityHistoryObject = activityhistory.toObject();
 * ```
 */
export type ActivityHistoryObject = ActivityHistory;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ActivityHistoryQuery = mongoose.Query<
  any,
  ActivityHistoryDocument,
  ActivityHistoryQueries
> &
  ActivityHistoryQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ActivityHistorySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ActivityHistoryQueries = {
  paginate: (
    this: ActivityHistoryQuery,
    ...args: any[]
  ) => ActivityHistoryQuery;
};

export type ActivityHistoryMethods = {};

export type ActivityHistoryStatics = {
  paginate: (this: ActivityHistoryModel, ...args: any[]) => any;
  paginateSubDocs: (this: ActivityHistoryModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ActivityHistory = mongoose.model<ActivityHistoryDocument, ActivityHistoryModel>("ActivityHistory", ActivityHistorySchema);
 * ```
 */
export type ActivityHistoryModel = mongoose.Model<
  ActivityHistoryDocument,
  ActivityHistoryQueries
> &
  ActivityHistoryStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new ActivityHistory schema instances:
 * ```
 * const ActivityHistorySchema: ActivityHistorySchema = new mongoose.Schema({ ... })
 * ```
 */
export type ActivityHistorySchema = mongoose.Schema<
  ActivityHistoryDocument,
  ActivityHistoryModel,
  ActivityHistoryMethods,
  ActivityHistoryQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ActivityHistory = mongoose.model<ActivityHistoryDocument, ActivityHistoryModel>("ActivityHistory", ActivityHistorySchema);
 * ```
 */
export type ActivityHistoryDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ActivityHistoryQueries
> &
  ActivityHistoryMethods & {
    title: string;
    details?: string;
    performDate: Date;
    model: string;
    modelId: mongoose.Types.ObjectId;
    metadata?: any | null;
    userId?: UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of CompanyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CompanyDocument.toObject()`. To avoid conflicts with model names, use the type alias `CompanyObject`.
 * ```
 * const companyObject = company.toObject();
 * ```
 */
export type Company = {
  name: string;
  countryId: Country;
  address: string;
  contactId: Contact;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CompanyDocument (type alias of `Company`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Company } from "../models"
 * import { CompanyObject } from "../interfaces/mongoose.gen.ts"
 *
 * const companyObject: CompanyObject = company.toObject();
 * ```
 */
export type CompanyObject = Company;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CompanyQuery = mongoose.Query<
  any,
  CompanyDocument,
  CompanyQueries
> &
  CompanyQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CompanySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CompanyQueries = {
  paginate: (this: CompanyQuery, ...args: any[]) => CompanyQuery;
};

export type CompanyMethods = {};

export type CompanyStatics = {
  paginate: (this: CompanyModel, ...args: any[]) => any;
  paginateSubDocs: (this: CompanyModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Company = mongoose.model<CompanyDocument, CompanyModel>("Company", CompanySchema);
 * ```
 */
export type CompanyModel = mongoose.Model<CompanyDocument, CompanyQueries> &
  CompanyStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Company schema instances:
 * ```
 * const CompanySchema: CompanySchema = new mongoose.Schema({ ... })
 * ```
 */
export type CompanySchema = mongoose.Schema<
  CompanyDocument,
  CompanyModel,
  CompanyMethods,
  CompanyQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Company = mongoose.model<CompanyDocument, CompanyModel>("Company", CompanySchema);
 * ```
 */
export type CompanyDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CompanyQueries
> &
  CompanyMethods & {
    name: string;
    countryId: CountryDocument;
    address: string;
    contactId: ContactDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ContactDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ContactDocument.toObject()`. To avoid conflicts with model names, use the type alias `ContactObject`.
 * ```
 * const contactObject = contact.toObject();
 * ```
 */
export type Contact = {
  name: string;
  lastName?: string;
  phoneNumber?: string;
  email?: string;
  website?: string;
  parentId?: Contact;
  type: "individual" | "company";
  countryId?: Country;
  state?: string;
  city?: string;
  zipCode?: string;
  streetAddress?: string;
  streetAddress2?: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  childIds: any;
};

/**
 * Lean version of ContactDocument (type alias of `Contact`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Contact } from "../models"
 * import { ContactObject } from "../interfaces/mongoose.gen.ts"
 *
 * const contactObject: ContactObject = contact.toObject();
 * ```
 */
export type ContactObject = Contact;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ContactQuery = mongoose.Query<
  any,
  ContactDocument,
  ContactQueries
> &
  ContactQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ContactSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ContactQueries = {
  paginate: (this: ContactQuery, ...args: any[]) => ContactQuery;
};

export type ContactMethods = {};

export type ContactStatics = {
  paginate: (this: ContactModel, ...args: any[]) => any;
  paginateSubDocs: (this: ContactModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Contact = mongoose.model<ContactDocument, ContactModel>("Contact", ContactSchema);
 * ```
 */
export type ContactModel = mongoose.Model<ContactDocument, ContactQueries> &
  ContactStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Contact schema instances:
 * ```
 * const ContactSchema: ContactSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ContactSchema = mongoose.Schema<
  ContactDocument,
  ContactModel,
  ContactMethods,
  ContactQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Contact = mongoose.model<ContactDocument, ContactModel>("Contact", ContactSchema);
 * ```
 */
export type ContactDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ContactQueries
> &
  ContactMethods & {
    name: string;
    lastName?: string;
    phoneNumber?: string;
    email?: string;
    website?: string;
    parentId?: ContactDocument;
    type: "individual" | "company";
    countryId?: CountryDocument;
    state?: string;
    city?: string;
    zipCode?: string;
    streetAddress?: string;
    streetAddress2?: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    childIds: any;
  };

/**
 * Lean version of CountryDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CountryDocument.toObject()`. To avoid conflicts with model names, use the type alias `CountryObject`.
 * ```
 * const countryObject = country.toObject();
 * ```
 */
export type Country = {
  name: string;
  code: string;
  currencyCode: string;
  currencySymbol: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CountryDocument (type alias of `Country`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Country } from "../models"
 * import { CountryObject } from "../interfaces/mongoose.gen.ts"
 *
 * const countryObject: CountryObject = country.toObject();
 * ```
 */
export type CountryObject = Country;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CountryQuery = mongoose.Query<
  any,
  CountryDocument,
  CountryQueries
> &
  CountryQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CountrySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CountryQueries = {
  paginate: (this: CountryQuery, ...args: any[]) => CountryQuery;
};

export type CountryMethods = {};

export type CountryStatics = {
  paginate: (this: CountryModel, ...args: any[]) => any;
  paginateSubDocs: (this: CountryModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Country = mongoose.model<CountryDocument, CountryModel>("Country", CountrySchema);
 * ```
 */
export type CountryModel = mongoose.Model<CountryDocument, CountryQueries> &
  CountryStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Country schema instances:
 * ```
 * const CountrySchema: CountrySchema = new mongoose.Schema({ ... })
 * ```
 */
export type CountrySchema = mongoose.Schema<
  CountryDocument,
  CountryModel,
  CountryMethods,
  CountryQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Country = mongoose.model<CountryDocument, CountryModel>("Country", CountrySchema);
 * ```
 */
export type CountryDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CountryQueries
> &
  CountryMethods & {
    name: string;
    code: string;
    currencyCode: string;
    currencySymbol: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of CRMDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CRMDocument.toObject()`. To avoid conflicts with model names, use the type alias `CRMObject`.
 * ```
 * const crmObject = crm.toObject();
 * ```
 */
export type CRM = {
  title: string;
  amount: number;
  currency?: string;
  stage?:
    | "prospecting"
    | "qualification"
    | "proposal"
    | "negotiation"
    | "closed-won"
    | "closed-lost";
  probability?: number;
  expectedCloseDate?: Date;
  actualCloseDate?: Date;
  contact: Contact;
  company: Company;
  owner?: User;
  description?: string;
  notes?: string;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CRMDocument (type alias of `CRM`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { CRM } from "../models"
 * import { CRMObject } from "../interfaces/mongoose.gen.ts"
 *
 * const crmObject: CRMObject = crm.toObject();
 * ```
 */
export type CRMObject = CRM;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CRMQuery = mongoose.Query<any, CRMDocument, CRMQueries> &
  CRMQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CRMSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CRMQueries = {
  paginate: (this: CRMQuery, ...args: any[]) => CRMQuery;
};

export type CRMMethods = {};

export type CRMStatics = {
  paginate: (this: CRMModel, ...args: any[]) => any;
  paginateSubDocs: (this: CRMModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CRM = mongoose.model<CRMDocument, CRMModel>("CRM", CRMSchema);
 * ```
 */
export type CRMModel = mongoose.Model<CRMDocument, CRMQueries> & CRMStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new CRM schema instances:
 * ```
 * const CRMSchema: CRMSchema = new mongoose.Schema({ ... })
 * ```
 */
export type CRMSchema = mongoose.Schema<
  CRMDocument,
  CRMModel,
  CRMMethods,
  CRMQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const CRM = mongoose.model<CRMDocument, CRMModel>("CRM", CRMSchema);
 * ```
 */
export type CRMDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CRMQueries
> &
  CRMMethods & {
    title: string;
    amount: number;
    currency?: string;
    stage?:
      | "prospecting"
      | "qualification"
      | "proposal"
      | "negotiation"
      | "closed-won"
      | "closed-lost";
    probability?: number;
    expectedCloseDate?: Date;
    actualCloseDate?: Date;
    contact: ContactDocument;
    company: CompanyDocument;
    owner?: UserDocument;
    description?: string;
    notes?: string;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of FacilityDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `FacilityDocument.toObject()`. To avoid conflicts with model names, use the type alias `FacilityObject`.
 * ```
 * const facilityObject = facility.toObject();
 * ```
 */
export type Facility = {
  name: string;
  contactId: Contact;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  rooms: any;
};

/**
 * Lean version of FacilityDocument (type alias of `Facility`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Facility } from "../models"
 * import { FacilityObject } from "../interfaces/mongoose.gen.ts"
 *
 * const facilityObject: FacilityObject = facility.toObject();
 * ```
 */
export type FacilityObject = Facility;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type FacilityQuery = mongoose.Query<
  any,
  FacilityDocument,
  FacilityQueries
> &
  FacilityQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `FacilitySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type FacilityQueries = {
  paginate: (this: FacilityQuery, ...args: any[]) => FacilityQuery;
};

export type FacilityMethods = {};

export type FacilityStatics = {
  paginate: (this: FacilityModel, ...args: any[]) => any;
  paginateSubDocs: (this: FacilityModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Facility = mongoose.model<FacilityDocument, FacilityModel>("Facility", FacilitySchema);
 * ```
 */
export type FacilityModel = mongoose.Model<FacilityDocument, FacilityQueries> &
  FacilityStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Facility schema instances:
 * ```
 * const FacilitySchema: FacilitySchema = new mongoose.Schema({ ... })
 * ```
 */
export type FacilitySchema = mongoose.Schema<
  FacilityDocument,
  FacilityModel,
  FacilityMethods,
  FacilityQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Facility = mongoose.model<FacilityDocument, FacilityModel>("Facility", FacilitySchema);
 * ```
 */
export type FacilityDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  FacilityQueries
> &
  FacilityMethods & {
    name: string;
    contactId: ContactDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    rooms: any;
  };

/**
 * Lean version of RoomDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoomDocument.toObject()`. To avoid conflicts with model names, use the type alias `RoomObject`.
 * ```
 * const roomObject = room.toObject();
 * ```
 */
export type Room = {
  name: string;
  code: string;
  address: string;
  facilityId: Facility;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of RoomDocument (type alias of `Room`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Room } from "../models"
 * import { RoomObject } from "../interfaces/mongoose.gen.ts"
 *
 * const roomObject: RoomObject = room.toObject();
 * ```
 */
export type RoomObject = Room;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type RoomQuery = mongoose.Query<any, RoomDocument, RoomQueries> &
  RoomQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `RoomSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type RoomQueries = {
  paginate: (this: RoomQuery, ...args: any[]) => RoomQuery;
};

export type RoomMethods = {};

export type RoomStatics = {
  paginate: (this: RoomModel, ...args: any[]) => any;
  paginateSubDocs: (this: RoomModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Room = mongoose.model<RoomDocument, RoomModel>("Room", RoomSchema);
 * ```
 */
export type RoomModel = mongoose.Model<RoomDocument, RoomQueries> & RoomStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Room schema instances:
 * ```
 * const RoomSchema: RoomSchema = new mongoose.Schema({ ... })
 * ```
 */
export type RoomSchema = mongoose.Schema<
  RoomDocument,
  RoomModel,
  RoomMethods,
  RoomQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Room = mongoose.model<RoomDocument, RoomModel>("Room", RoomSchema);
 * ```
 */
export type RoomDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  RoomQueries
> &
  RoomMethods & {
    name: string;
    code: string;
    address: string;
    facilityId: FacilityDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of MaintenanceWindowDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `MaintenanceWindowDocument.toObject()`. To avoid conflicts with model names, use the type alias `MaintenanceWindowObject`.
 * ```
 * const maintenancewindowObject = maintenancewindow.toObject();
 * ```
 */
export type MaintenanceWindow = {
  name: string;
  daysBefore: number;
  daysAfter: number;
  recurrency:
    | "daily"
    | "weekly"
    | "monthly"
    | "quarterly"
    | "semi-anually"
    | "annually";
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of MaintenanceWindowDocument (type alias of `MaintenanceWindow`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { MaintenanceWindow } from "../models"
 * import { MaintenanceWindowObject } from "../interfaces/mongoose.gen.ts"
 *
 * const maintenancewindowObject: MaintenanceWindowObject = maintenancewindow.toObject();
 * ```
 */
export type MaintenanceWindowObject = MaintenanceWindow;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type MaintenanceWindowQuery = mongoose.Query<
  any,
  MaintenanceWindowDocument,
  MaintenanceWindowQueries
> &
  MaintenanceWindowQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `MaintenanceWindowSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type MaintenanceWindowQueries = {
  paginate: (
    this: MaintenanceWindowQuery,
    ...args: any[]
  ) => MaintenanceWindowQuery;
};

export type MaintenanceWindowMethods = {
  parseRecurrencyForDayjs: (
    this: MaintenanceWindowDocument,
    ...args: any[]
  ) => any;
};

export type MaintenanceWindowStatics = {
  paginate: (this: MaintenanceWindowModel, ...args: any[]) => any;
  paginateSubDocs: (this: MaintenanceWindowModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const MaintenanceWindow = mongoose.model<MaintenanceWindowDocument, MaintenanceWindowModel>("MaintenanceWindow", MaintenanceWindowSchema);
 * ```
 */
export type MaintenanceWindowModel = mongoose.Model<
  MaintenanceWindowDocument,
  MaintenanceWindowQueries
> &
  MaintenanceWindowStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new MaintenanceWindow schema instances:
 * ```
 * const MaintenanceWindowSchema: MaintenanceWindowSchema = new mongoose.Schema({ ... })
 * ```
 */
export type MaintenanceWindowSchema = mongoose.Schema<
  MaintenanceWindowDocument,
  MaintenanceWindowModel,
  MaintenanceWindowMethods,
  MaintenanceWindowQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const MaintenanceWindow = mongoose.model<MaintenanceWindowDocument, MaintenanceWindowModel>("MaintenanceWindow", MaintenanceWindowSchema);
 * ```
 */
export type MaintenanceWindowDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  MaintenanceWindowQueries
> &
  MaintenanceWindowMethods & {
    name: string;
    daysBefore: number;
    daysAfter: number;
    recurrency:
      | "daily"
      | "weekly"
      | "monthly"
      | "quarterly"
      | "semi-anually"
      | "annually";
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ProductCommissioningAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductCommissioningDocument.toObject()`.
 * ```
 * const productcommissioningObject = productcommissioning.toObject();
 * ```
 */
export type ProductCommissioningAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProductCommissioningDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductCommissioningDocument.toObject()`. To avoid conflicts with model names, use the type alias `ProductCommissioningObject`.
 * ```
 * const productcommissioningObject = productcommissioning.toObject();
 * ```
 */
export type ProductCommissioning = {
  outcome: "fail" | "pass";
  details?: string;
  attachments: ProductCommissioningAttachment[];
  productId: Product;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProductCommissioningDocument (type alias of `ProductCommissioning`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { ProductCommissioning } from "../models"
 * import { ProductCommissioningObject } from "../interfaces/mongoose.gen.ts"
 *
 * const productcommissioningObject: ProductCommissioningObject = productcommissioning.toObject();
 * ```
 */
export type ProductCommissioningObject = ProductCommissioning;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ProductCommissioningQuery = mongoose.Query<
  any,
  ProductCommissioningDocument,
  ProductCommissioningQueries
> &
  ProductCommissioningQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ProductCommissioningSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ProductCommissioningQueries = {
  paginate: (
    this: ProductCommissioningQuery,
    ...args: any[]
  ) => ProductCommissioningQuery;
};

export type ProductCommissioningMethods = {};

export type ProductCommissioningStatics = {
  paginate: (this: ProductCommissioningModel, ...args: any[]) => any;
  paginateSubDocs: (this: ProductCommissioningModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ProductCommissioning = mongoose.model<ProductCommissioningDocument, ProductCommissioningModel>("ProductCommissioning", ProductCommissioningSchema);
 * ```
 */
export type ProductCommissioningModel = mongoose.Model<
  ProductCommissioningDocument,
  ProductCommissioningQueries
> &
  ProductCommissioningStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new ProductCommissioning schema instances:
 * ```
 * const ProductCommissioningSchema: ProductCommissioningSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ProductCommissioningSchema = mongoose.Schema<
  ProductCommissioningDocument,
  ProductCommissioningModel,
  ProductCommissioningMethods,
  ProductCommissioningQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `ProductCommissioningDocument["attachments"]` element.
 */
export type ProductCommissioningAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ProductCommissioning = mongoose.model<ProductCommissioningDocument, ProductCommissioningModel>("ProductCommissioning", ProductCommissioningSchema);
 * ```
 */
export type ProductCommissioningDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ProductCommissioningQueries
> &
  ProductCommissioningMethods & {
    outcome: "fail" | "pass";
    details?: string;
    attachments: mongoose.Types.DocumentArray<ProductCommissioningAttachmentDocument>;
    productId: ProductDocument;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ProductMaintenanceAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductMaintenanceDocument.toObject()`.
 * ```
 * const productmaintenanceObject = productmaintenance.toObject();
 * ```
 */
export type ProductMaintenanceAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProductMaintenanceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductMaintenanceDocument.toObject()`. To avoid conflicts with model names, use the type alias `ProductMaintenanceObject`.
 * ```
 * const productmaintenanceObject = productmaintenance.toObject();
 * ```
 */
export type ProductMaintenance = {
  name: string;
  description?: string;
  notes?: string;
  attachments: ProductMaintenanceAttachment[];
  productId: Product;
  dateStart?: Date;
  dateEnd?: Date;
  type: "service" | "preventive-maintenance";
  manual?: boolean;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProductMaintenanceDocument (type alias of `ProductMaintenance`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { ProductMaintenance } from "../models"
 * import { ProductMaintenanceObject } from "../interfaces/mongoose.gen.ts"
 *
 * const productmaintenanceObject: ProductMaintenanceObject = productmaintenance.toObject();
 * ```
 */
export type ProductMaintenanceObject = ProductMaintenance;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ProductMaintenanceQuery = mongoose.Query<
  any,
  ProductMaintenanceDocument,
  ProductMaintenanceQueries
> &
  ProductMaintenanceQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ProductMaintenanceSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ProductMaintenanceQueries = {
  paginate: (
    this: ProductMaintenanceQuery,
    ...args: any[]
  ) => ProductMaintenanceQuery;
};

export type ProductMaintenanceMethods = {};

export type ProductMaintenanceStatics = {
  paginate: (this: ProductMaintenanceModel, ...args: any[]) => any;
  paginateSubDocs: (this: ProductMaintenanceModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ProductMaintenance = mongoose.model<ProductMaintenanceDocument, ProductMaintenanceModel>("ProductMaintenance", ProductMaintenanceSchema);
 * ```
 */
export type ProductMaintenanceModel = mongoose.Model<
  ProductMaintenanceDocument,
  ProductMaintenanceQueries
> &
  ProductMaintenanceStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new ProductMaintenance schema instances:
 * ```
 * const ProductMaintenanceSchema: ProductMaintenanceSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ProductMaintenanceSchema = mongoose.Schema<
  ProductMaintenanceDocument,
  ProductMaintenanceModel,
  ProductMaintenanceMethods,
  ProductMaintenanceQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `ProductMaintenanceDocument["attachments"]` element.
 */
export type ProductMaintenanceAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ProductMaintenance = mongoose.model<ProductMaintenanceDocument, ProductMaintenanceModel>("ProductMaintenance", ProductMaintenanceSchema);
 * ```
 */
export type ProductMaintenanceDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ProductMaintenanceQueries
> &
  ProductMaintenanceMethods & {
    name: string;
    description?: string;
    notes?: string;
    attachments: mongoose.Types.DocumentArray<ProductMaintenanceAttachmentDocument>;
    productId: ProductDocument;
    dateStart?: Date;
    dateEnd?: Date;
    type: "service" | "preventive-maintenance";
    manual?: boolean;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ProductTypeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductTypeDocument.toObject()`. To avoid conflicts with model names, use the type alias `ProductTypeObject`.
 * ```
 * const producttypeObject = producttype.toObject();
 * ```
 */
export type ProductType = {
  name: string;
  description?: string;
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProductTypeDocument (type alias of `ProductType`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { ProductType } from "../models"
 * import { ProductTypeObject } from "../interfaces/mongoose.gen.ts"
 *
 * const producttypeObject: ProductTypeObject = producttype.toObject();
 * ```
 */
export type ProductTypeObject = ProductType;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ProductTypeQuery = mongoose.Query<
  any,
  ProductTypeDocument,
  ProductTypeQueries
> &
  ProductTypeQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ProductTypeSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ProductTypeQueries = {
  paginate: (this: ProductTypeQuery, ...args: any[]) => ProductTypeQuery;
};

export type ProductTypeMethods = {};

export type ProductTypeStatics = {
  paginate: (this: ProductTypeModel, ...args: any[]) => any;
  paginateSubDocs: (this: ProductTypeModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ProductType = mongoose.model<ProductTypeDocument, ProductTypeModel>("ProductType", ProductTypeSchema);
 * ```
 */
export type ProductTypeModel = mongoose.Model<
  ProductTypeDocument,
  ProductTypeQueries
> &
  ProductTypeStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new ProductType schema instances:
 * ```
 * const ProductTypeSchema: ProductTypeSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ProductTypeSchema = mongoose.Schema<
  ProductTypeDocument,
  ProductTypeModel,
  ProductTypeMethods,
  ProductTypeQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const ProductType = mongoose.model<ProductTypeDocument, ProductTypeModel>("ProductType", ProductTypeSchema);
 * ```
 */
export type ProductTypeDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ProductTypeQueries
> &
  ProductTypeMethods & {
    name: string;
    description?: string;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of ProductAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductDocument.toObject()`.
 * ```
 * const productObject = product.toObject();
 * ```
 */
export type ProductAttachment = {
  fileId: mongoose.Types.ObjectId;
  name: string;
  mimeType: string;
  size: number;
  fileMetadata?: any;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of ProductDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ProductDocument.toObject()`. To avoid conflicts with model names, use the type alias `ProductObject`.
 * ```
 * const productObject = product.toObject();
 * ```
 */
export type Product = {
  productTypeIds: ProductType[];
  vendorIds?: Contact[];
  makeIds: Contact[];
  productModel: string;
  serialNumber: string;
  acquiredDate: Date;
  acquiredPrice?: number;
  currentPrice?: number;
  condition?: "excellent" | "good" | "fair" | "poor";
  maintenanceWindowIds: MaintenanceWindow[];
  photo?: mongoose.Types.ObjectId;
  locationId?: Room;
  warrantyDate?: Date;
  remarks?: string;
  status?:
    | "active"
    | "awaiting-commissioning"
    | "under-service"
    | "decommissioned"
    | "in-pm";
  minMaintenanceDate?: Date;
  maintenanceDate?: Date;
  maxMaintenanceDate?: Date;
  attachments: ProductAttachment[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  productCommission: any;
  productMaintenances: any;
};

/**
 * Lean version of ProductDocument (type alias of `Product`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Product } from "../models"
 * import { ProductObject } from "../interfaces/mongoose.gen.ts"
 *
 * const productObject: ProductObject = product.toObject();
 * ```
 */
export type ProductObject = Product;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ProductQuery = mongoose.Query<
  any,
  ProductDocument,
  ProductQueries
> &
  ProductQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ProductSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ProductQueries = {
  paginate: (this: ProductQuery, ...args: any[]) => ProductQuery;
};

export type ProductMethods = {};

export type ProductStatics = {
  paginate: (this: ProductModel, ...args: any[]) => any;
  paginateSubDocs: (this: ProductModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Product = mongoose.model<ProductDocument, ProductModel>("Product", ProductSchema);
 * ```
 */
export type ProductModel = mongoose.Model<ProductDocument, ProductQueries> &
  ProductStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Product schema instances:
 * ```
 * const ProductSchema: ProductSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ProductSchema = mongoose.Schema<
  ProductDocument,
  ProductModel,
  ProductMethods,
  ProductQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `ProductDocument["attachments"]` element.
 */
export type ProductAttachmentDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    fileId: mongoose.Types.ObjectId;
    name: string;
    mimeType: string;
    size: number;
    fileMetadata?: any;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Product = mongoose.model<ProductDocument, ProductModel>("Product", ProductSchema);
 * ```
 */
export type ProductDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ProductQueries
> &
  ProductMethods & {
    productTypeIds: mongoose.Types.Array<ProductTypeDocument>;
    vendorIds?: mongoose.Types.Array<ContactDocument>;
    makeIds: mongoose.Types.Array<ContactDocument>;
    productModel: string;
    serialNumber: string;
    acquiredDate: Date;
    acquiredPrice?: number;
    currentPrice?: number;
    condition?: "excellent" | "good" | "fair" | "poor";
    maintenanceWindowIds: mongoose.Types.Array<MaintenanceWindowDocument>;
    photo?: mongoose.Types.ObjectId;
    locationId?: RoomDocument;
    warrantyDate?: Date;
    remarks?: string;
    status?:
      | "active"
      | "awaiting-commissioning"
      | "under-service"
      | "decommissioned"
      | "in-pm";
    minMaintenanceDate?: Date;
    maintenanceDate?: Date;
    maxMaintenanceDate?: Date;
    attachments: mongoose.Types.DocumentArray<ProductAttachmentDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
    productCommission: any;
    productMaintenances: any;
  };

/**
 * Lean version of ReportingDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ReportingDocument.toObject()`. To avoid conflicts with model names, use the type alias `ReportingObject`.
 * ```
 * const reportingObject = reporting.toObject();
 * ```
 */
export type Reporting = {
  template: string;
  model: string;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of ReportingDocument (type alias of `Reporting`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Reporting } from "../models"
 * import { ReportingObject } from "../interfaces/mongoose.gen.ts"
 *
 * const reportingObject: ReportingObject = reporting.toObject();
 * ```
 */
export type ReportingObject = Reporting;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type ReportingQuery = mongoose.Query<
  any,
  ReportingDocument,
  ReportingQueries
> &
  ReportingQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `ReportingSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type ReportingQueries = {
  paginate: (this: ReportingQuery, ...args: any[]) => ReportingQuery;
};

export type ReportingMethods = {};

export type ReportingStatics = {
  paginate: (this: ReportingModel, ...args: any[]) => any;
  paginateSubDocs: (this: ReportingModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Reporting = mongoose.model<ReportingDocument, ReportingModel>("Reporting", ReportingSchema);
 * ```
 */
export type ReportingModel = mongoose.Model<
  ReportingDocument,
  ReportingQueries
> &
  ReportingStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Reporting schema instances:
 * ```
 * const ReportingSchema: ReportingSchema = new mongoose.Schema({ ... })
 * ```
 */
export type ReportingSchema = mongoose.Schema<
  ReportingDocument,
  ReportingModel,
  ReportingMethods,
  ReportingQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Reporting = mongoose.model<ReportingDocument, ReportingModel>("Reporting", ReportingSchema);
 * ```
 */
export type ReportingDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  ReportingQueries
> &
  ReportingMethods & {
    template: string;
    model: string;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Lean version of PolicyConditionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `PolicyDocument.toObject()`.
 * ```
 * const policyObject = policy.toObject();
 * ```
 */
export type PolicyCondition = {
  key: string;
  operator: "==" | "!=" | ">" | "<" | "in";
  value: any;
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of PolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `PolicyDocument.toObject()`. To avoid conflicts with model names, use the type alias `PolicyObject`.
 * ```
 * const policyObject = policy.toObject();
 * ```
 */
export type Policy = {
  name: string;
  resource: string;
  type: "view" | "menu" | "model";
  conditions: PolicyCondition[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of PolicyDocument (type alias of `Policy`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Policy } from "../models"
 * import { PolicyObject } from "../interfaces/mongoose.gen.ts"
 *
 * const policyObject: PolicyObject = policy.toObject();
 * ```
 */
export type PolicyObject = Policy;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type PolicyQuery = mongoose.Query<any, PolicyDocument, PolicyQueries> &
  PolicyQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `PolicySchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type PolicyQueries = {
  paginate: (this: PolicyQuery, ...args: any[]) => PolicyQuery;
};

export type PolicyMethods = {};

export type PolicyStatics = {
  paginate: (this: PolicyModel, ...args: any[]) => any;
  paginateSubDocs: (this: PolicyModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Policy = mongoose.model<PolicyDocument, PolicyModel>("Policy", PolicySchema);
 * ```
 */
export type PolicyModel = mongoose.Model<PolicyDocument, PolicyQueries> &
  PolicyStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Policy schema instances:
 * ```
 * const PolicySchema: PolicySchema = new mongoose.Schema({ ... })
 * ```
 */
export type PolicySchema = mongoose.Schema<
  PolicyDocument,
  PolicyModel,
  PolicyMethods,
  PolicyQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `PolicyDocument["conditions"]` element.
 */
export type PolicyConditionDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    key: string;
    operator: "==" | "!=" | ">" | "<" | "in";
    value: any;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Policy = mongoose.model<PolicyDocument, PolicyModel>("Policy", PolicySchema);
 * ```
 */
export type PolicyDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  PolicyQueries
> &
  PolicyMethods & {
    name: string;
    resource: string;
    type: "view" | "menu" | "model";
    conditions: mongoose.Types.DocumentArray<PolicyConditionDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of RolePolicyDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoleDocument.toObject()`.
 * ```
 * const roleObject = role.toObject();
 * ```
 */
export type RolePolicy = {
  policyId: Policy;
  actions: ("create" | "read" | "update" | "delete")[];
  _id: mongoose.Types.ObjectId;
};

/**
 * Lean version of RoleDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoleDocument.toObject()`. To avoid conflicts with model names, use the type alias `RoleObject`.
 * ```
 * const roleObject = role.toObject();
 * ```
 */
export type Role = {
  name: string;
  policies: RolePolicy[];
  active?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of RoleDocument (type alias of `Role`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Role } from "../models"
 * import { RoleObject } from "../interfaces/mongoose.gen.ts"
 *
 * const roleObject: RoleObject = role.toObject();
 * ```
 */
export type RoleObject = Role;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type RoleQuery = mongoose.Query<any, RoleDocument, RoleQueries> &
  RoleQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `RoleSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type RoleQueries = {
  paginate: (this: RoleQuery, ...args: any[]) => RoleQuery;
};

export type RoleMethods = {};

export type RoleStatics = {
  paginate: (this: RoleModel, ...args: any[]) => any;
  paginateSubDocs: (this: RoleModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Role = mongoose.model<RoleDocument, RoleModel>("Role", RoleSchema);
 * ```
 */
export type RoleModel = mongoose.Model<RoleDocument, RoleQueries> & RoleStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Role schema instances:
 * ```
 * const RoleSchema: RoleSchema = new mongoose.Schema({ ... })
 * ```
 */
export type RoleSchema = mongoose.Schema<
  RoleDocument,
  RoleModel,
  RoleMethods,
  RoleQueries
>;

/**
 * Mongoose Subdocument type
 *
 * Type of `RoleDocument["policies"]` element.
 */
export type RolePolicyDocument =
  mongoose.Types.Subdocument<mongoose.Types.ObjectId> & {
    policyId: PolicyDocument;
    actions: mongoose.Types.Array<"create" | "read" | "update" | "delete">;
    _id: mongoose.Types.ObjectId;
  };

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Role = mongoose.model<RoleDocument, RoleModel>("Role", RoleSchema);
 * ```
 */
export type RoleDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  RoleQueries
> &
  RoleMethods & {
    name: string;
    policies: mongoose.Types.DocumentArray<RolePolicyDocument>;
    active?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of UserDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`. To avoid conflicts with model names, use the type alias `UserObject`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type User = {
  authId: string;
  provider: "google.com" | "password";
  username: string;
  email: string;
  picture?: string;
  uploadedPictureId?: mongoose.Types.ObjectId;
  active?: boolean;
  roles: Role[];
  contactId?: Contact;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of UserDocument (type alias of `User`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { User } from "../models"
 * import { UserObject } from "../interfaces/mongoose.gen.ts"
 *
 * const userObject: UserObject = user.toObject();
 * ```
 */
export type UserObject = User;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type UserQuery = mongoose.Query<any, UserDocument, UserQueries> &
  UserQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `UserSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type UserQueries = {
  paginate: (this: UserQuery, ...args: any[]) => UserQuery;
};

export type UserMethods = {};

export type UserStatics = {
  paginate: (this: UserModel, ...args: any[]) => any;
  paginateSubDocs: (this: UserModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserModel = mongoose.Model<UserDocument, UserQueries> & UserStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new User schema instances:
 * ```
 * const UserSchema: UserSchema = new mongoose.Schema({ ... })
 * ```
 */
export type UserSchema = mongoose.Schema<
  UserDocument,
  UserModel,
  UserMethods,
  UserQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  UserQueries
> &
  UserMethods & {
    authId: string;
    provider: "google.com" | "password";
    username: string;
    email: string;
    picture?: string;
    uploadedPictureId?: mongoose.Types.ObjectId;
    active?: boolean;
    roles: mongoose.Types.Array<RoleDocument>;
    contactId?: ContactDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<
        infer U
      >
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module "mongoose" {
  interface Query<ResultType, DocType, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}
