export enum ValuationMethodTypeEnum {
  TRANSACTIONAL_VALUE = "01",
  SIMILAR_GOODS = "02",
}

export enum EBCDTypeEnum {
  SENT_CSV = "SENT_CSV", // * Sent CSV from US to GOVERNMENT
  FILE_ERROR_CSV = "FILE_ERROR_CSV", // * ...E.0001
  FORMAT_ERROR_PDF = "FORMAT_ERROR_PDF", // * SQR.PDF
  FORMAT_ERROR_TXT = "FORMAT_ERROR_TXT", // * SQR.TXT
  RELEASE_CSV = "RELEASE_CSV", // * REL.CSV
  RELEASE_PDF = "RELEASE_PDF", // * REL.PDF
  RELEASE_TXT = "RELEASE_TXT", // * REL.TXT
  RECEIPT_TXT = "RECEIPT_TXT", // * REC.TXT
}

export enum BCDStatusTypeEnum {
  DRAFT = "DRAFT",
  PENDING_RESPONSE = "PENDING_RESPONSE",
  FAILED = "FAILED",
  PENDING_QUERY = "PENDING_QUERY",
  SUBMITTED = "SUBMITTED",
}
