services:
  localhost_mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - ./mongo_data:/data/local_db
      # Para guardar el estado de este contenedor
      # Agregar al .gitignore esta carpeta,
      # para no subirla al git
